/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.signup;

import hallconnect.database.CentralController;
import hallconnect.database.DbConnection;
import hallconnect.signup.loginPage;
import hallconnect.room.RoomSelection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SecuirityForm extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    private String hall;
    private String name;
    private String reg;
    private int session;
    private String dob;
    private String blood;
    private String contact;
    private String email;
    private String username;
    private String pass;
    
    private String dept;
   

    /**
     * Creates new form Registration
     */
    public SecuirityForm() {
        initComponents();
    }

    public SecuirityForm(CentralController controller, String hall,String dept, String name, String reg, int session, String dob, String blood, String contact, String email, String username, String pass) {
        this.controller = controller;
        this.hall = hall;
        this.name = name;
        this.reg = reg;
        this.session = session;
        this.dob = dob;
        this.blood = blood;
        this.contact = contact;
        this.email = email;
        this.username = username;
        this.pass = pass;
        this.dept=dept;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect1 = new javax.swing.JLabel();
        label_hallconnect = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_room = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_home6 = new javax.swing.JLabel();
        label_home7 = new javax.swing.JLabel();
        txt_answer = new javax.swing.JTextField();
        combo_question = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        label_home27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_home21 = new javax.swing.JLabel();
        label_home23 = new javax.swing.JLabel();
        label_home24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        label_home22 = new javax.swing.JLabel();
        combo_room_1 = new javax.swing.JComboBox<>();
        combo_floor_1 = new javax.swing.JComboBox<>();
        label_home25 = new javax.swing.JLabel();
        label_home26 = new javax.swing.JLabel();
        combo_floor_2 = new javax.swing.JComboBox<>();
        combo_room_2 = new javax.swing.JComboBox<>();
        combo_floor_3 = new javax.swing.JComboBox<>();
        combo_room_3 = new javax.swing.JComboBox<>();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect1.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect1.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 140));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("ENTER SECURITY QUESTION AND ROOM PREFERENCE");
        panel_parent.add(label_hallconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 54));

        btn_submit.setBackground(new java.awt.Color(102, 102, 102));
        btn_submit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/signup.png"))); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 170, 54));

        btn_room.setBackground(new java.awt.Color(102, 102, 102));
        btn_room.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_room.setForeground(new java.awt.Color(255, 255, 255));
        btn_room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/icons8-eye.gif"))); // NOI18N
        btn_room.setText("SEE ROOM");
        btn_room.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomActionPerformed(evt);
            }
        });
        panel_parent.add(btn_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 190, 54));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home6.setForeground(new java.awt.Color(255, 255, 255));
        label_home6.setText("QUESTION :");
        jPanel3.add(label_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        label_home7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home7.setForeground(new java.awt.Color(255, 255, 255));
        label_home7.setText("ANSWER :");
        jPanel3.add(label_home7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 30));

        txt_answer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel3.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 430, 40));

        combo_question.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite pet's name?", "What is your favorite color?", "What is your favorite food?", "What is your favorite movie?", "What is your favorite book?", "What is your mother's maiden name?", "What city were you born in?", "What was your childhood nickname?" }));
        jPanel3.add(combo_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 430, 40));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        label_home27.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home27.setForeground(new java.awt.Color(255, 255, 255));
        label_home27.setText("Select Question & Answer");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(label_home27)
                .addGap(99, 99, 99))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_home27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 640, 70));

        panel_parent.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 700, 330));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home21.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        label_home21.setForeground(new java.awt.Color(255, 255, 255));
        label_home21.setText("ROOM");
        jPanel4.add(label_home21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 30));

        label_home23.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        label_home23.setForeground(new java.awt.Color(255, 255, 255));
        label_home23.setText("Choose Room-2    :");
        jPanel4.add(label_home23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        label_home24.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        label_home24.setForeground(new java.awt.Color(255, 255, 255));
        label_home24.setText("Choose Room-3    :");
        jPanel4.add(label_home24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        label_home22.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home22.setForeground(new java.awt.Color(255, 255, 255));
        label_home22.setText("Select Room Priority");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(label_home22)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(label_home22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 650, 70));

        combo_room_1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_room_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "106", "107", "108", "109" }));
        jPanel4.add(combo_room_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, 30));

        combo_floor_1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_floor_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th" }));
        combo_floor_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_floor_1ActionPerformed(evt);
            }
        });
        combo_floor_1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_floor_1PropertyChange(evt);
            }
        });
        jPanel4.add(combo_floor_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 160, 30));

        label_home25.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        label_home25.setForeground(new java.awt.Color(255, 255, 255));
        label_home25.setText("Choose Room-1    :");
        jPanel4.add(label_home25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        label_home26.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        label_home26.setForeground(new java.awt.Color(255, 255, 255));
        label_home26.setText("FLOOR");
        jPanel4.add(label_home26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 30));

        combo_floor_2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_floor_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th" }));
        combo_floor_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_floor_2ActionPerformed(evt);
            }
        });
        combo_floor_2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_floor_2PropertyChange(evt);
            }
        });
        jPanel4.add(combo_floor_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 160, 30));

        combo_room_2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_room_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "106", "107", "108", "109" }));
        jPanel4.add(combo_room_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 190, 30));

        combo_floor_3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_floor_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th" }));
        combo_floor_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_floor_3ActionPerformed(evt);
            }
        });
        combo_floor_3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_floor_3PropertyChange(evt);
            }
        });
        jPanel4.add(combo_floor_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 160, 30));

        combo_room_3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_room_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "106", "107", "108", "109" }));
        jPanel4.add(combo_room_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, 30));

        panel_parent.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 730, 330));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, 140, 54));

        getContentPane().add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String question = combo_question.getSelectedItem().toString();
        String ans = txt_answer.getText();
        String room1=combo_room_1.getSelectedItem().toString();
        String room2 = combo_room_2.getSelectedItem().toString();
        String room3=combo_room_3.getSelectedItem().toString();
        if (ans.equals("")) {
            JOptionPane.showMessageDialog(this, "PLEASE ENTER QUESTION AND ANSWER");
        } else {

            try {
                Connection con = DbConnection.getConnection();
                PreparedStatement pst = con.prepareStatement("INSERT INTO pending (name, reg, session, dob, blood, contact, email, username,pass,question, ans) "
                        + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                PreparedStatement pst2 = con.prepareStatement("INSERT INTO pending_room (hall_name,username,room1,room2,room3,dept) VALUES(?,?,?,?,?,?)");
                pst2.setString(1, hall);
                pst2.setString(2, username);
                pst2.setString(3, room1);
                pst2.setString(4, room2);
                pst2.setString(5, room3);
                pst2.setString(6, dept);
                
                pst.setString(1, name);
                pst.setString(2, reg);
                pst.setInt(3, session);
                pst.setString(4, dob);
                pst.setString(5, blood);
                pst.setString(6, contact);
                pst.setString(7, email);
                pst.setString(8, username);
                pst.setString(9, pass);
                pst.setString(10, question);
                pst.setString(11, ans);

// Execute the query
                int rowCount = pst.executeUpdate();
                int rowcount2=pst2.executeUpdate();
                if (rowCount > 0 && rowcount2>0) {
                    JOptionPane.showMessageDialog(this, "SIGNUP SUCCESSFULL");
                    loginPage lg = new loginPage(controller);
                    lg.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "SIGNUP FAILED");
                }
                

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomActionPerformed
        // TODO add your handling code here:
        controller.addFrame(this);
        RoomSelection roomselection = new RoomSelection(controller, hall);
        roomselection.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_roomActionPerformed

    private void combo_floor_1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_floor_1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_combo_floor_1PropertyChange

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:

        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void combo_floor_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_floor_1ActionPerformed
        // TODO add your handling code here:
        if (combo_floor_1.getSelectedItem().toString().equals("1st")) {

            combo_room_1.removeAllItems();

            combo_room_1.addItem("101");
            combo_room_1.addItem("102");
            combo_room_1.addItem("103");

            combo_room_1.addItem("107");
            combo_room_1.addItem("108");
            combo_room_1.addItem("109");

        } else if (combo_floor_1.getSelectedItem().toString().equals("2nd")) {

            combo_room_1.removeAllItems();

            combo_room_1.addItem("201");
            combo_room_1.addItem("202");
            combo_room_1.addItem("203");

            combo_room_1.addItem("204");
            combo_room_1.addItem("205");
            combo_room_1.addItem("206");

            combo_room_1.addItem("shared");

            combo_room_1.addItem("207");
            combo_room_1.addItem("208");
            combo_room_1.addItem("209");
        } else if (combo_floor_1.getSelectedItem().toString().equals("3rd")) {

            combo_room_1.removeAllItems();

            combo_room_1.addItem("301");
            combo_room_1.addItem("302");
            combo_room_1.addItem("303");

            combo_room_1.addItem("304");
            combo_room_1.addItem("305");
            combo_room_1.addItem("306");

            combo_room_1.addItem("307");
            combo_room_1.addItem("308");
            combo_room_1.addItem("309");
        } else if (combo_floor_1.getSelectedItem().toString().equals("4th")) {

            combo_room_1.removeAllItems();

            combo_room_1.addItem("401");
            combo_room_1.addItem("402");
            combo_room_1.addItem("403");

            combo_room_1.addItem("404");
            combo_room_1.addItem("405");
            combo_room_1.addItem("406");

            combo_room_1.addItem("407");
            combo_room_1.addItem("408");
            combo_room_1.addItem("409");
        } else if (combo_floor_1.getSelectedItem().toString().equals("5th")) {

            combo_room_1.removeAllItems();

            combo_room_1.addItem("501");
            combo_room_1.addItem("502");
            combo_room_1.addItem("503");

            combo_room_1.addItem("504");
            combo_room_1.addItem("505");
            combo_room_1.addItem("506");

            combo_room_1.addItem("507");
            combo_room_1.addItem("508");
            combo_room_1.addItem("509");
        }

    }//GEN-LAST:event_combo_floor_1ActionPerformed

    private void combo_floor_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_floor_2ActionPerformed
        // TODO add your handling code here:

        if (combo_floor_2.getSelectedItem().toString().equals("1st")) {
            combo_room_2.removeAllItems();

            combo_room_2.addItem("101");
            combo_room_2.addItem("102");
            combo_room_2.addItem("103");

            combo_room_2.addItem("107");
            combo_room_2.addItem("108");
            combo_room_2.addItem("109");

        } else if (combo_floor_2.getSelectedItem().toString().equals("2nd")) {

            combo_room_2.removeAllItems();

            combo_room_2.addItem("201");
            combo_room_2.addItem("202");
            combo_room_2.addItem("203");

            combo_room_2.addItem("204");
            combo_room_2.addItem("205");
            combo_room_2.addItem("206");

            combo_room_2.addItem("shared");

            combo_room_2.addItem("207");
            combo_room_2.addItem("208");
            combo_room_2.addItem("209");
        } else if (combo_floor_2.getSelectedItem().toString().equals("3rd")) {

            combo_room_2.removeAllItems();

            combo_room_2.addItem("301");
            combo_room_2.addItem("302");
            combo_room_2.addItem("303");

            combo_room_2.addItem("304");
            combo_room_2.addItem("305");
            combo_room_2.addItem("306");

            combo_room_2.addItem("307");
            combo_room_2.addItem("308");
            combo_room_2.addItem("309");
        } else if (combo_floor_2.getSelectedItem().toString().equals("4th")) {

            combo_room_2.removeAllItems();

            combo_room_2.addItem("401");
            combo_room_2.addItem("402");
            combo_room_2.addItem("403");

            combo_room_2.addItem("404");
            combo_room_2.addItem("405");
            combo_room_2.addItem("406");

            combo_room_2.addItem("407");
            combo_room_2.addItem("408");
            combo_room_2.addItem("409");
        } else if (combo_floor_2.getSelectedItem().toString().equals("5th")) {

            combo_room_2.removeAllItems();

            combo_room_2.addItem("501");
            combo_room_2.addItem("502");
            combo_room_2.addItem("503");

            combo_room_2.addItem("504");
            combo_room_2.addItem("505");
            combo_room_2.addItem("506");

            combo_room_2.addItem("507");
            combo_room_2.addItem("508");
            combo_room_2.addItem("509");
        }


    }//GEN-LAST:event_combo_floor_2ActionPerformed

    private void combo_floor_2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_floor_2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_floor_2PropertyChange

    private void combo_floor_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_floor_3ActionPerformed
        // TODO add your handling code here:

        if (combo_floor_3.getSelectedItem().toString().equals("1st")) {
            combo_room_3.removeAllItems();
            combo_room_3.addItem("101");
            combo_room_3.addItem("102");
            combo_room_3.addItem("103");
            combo_room_3.addItem("107");
            combo_room_3.addItem("108");
            combo_room_3.addItem("109");

        } else if (combo_floor_3.getSelectedItem().toString().equals("2nd")) {

            combo_room_3.removeAllItems();
            combo_room_3.addItem("201");
            combo_room_3.addItem("202");
            combo_room_3.addItem("203");
            combo_room_3.addItem("204");
            combo_room_3.addItem("205");
            combo_room_3.addItem("206");
            combo_room_3.addItem("shared");

            combo_room_3.addItem("207");
            combo_room_3.addItem("208");
            combo_room_3.addItem("209");

        } else if (combo_floor_3.getSelectedItem().toString().equals("3rd")) {

            combo_room_3.removeAllItems();
            combo_room_3.addItem("301");
            combo_room_3.addItem("302");
            combo_room_3.addItem("303");
            combo_room_3.addItem("304");
            combo_room_3.addItem("305");
            combo_room_3.addItem("306");

            combo_room_3.addItem("307");
            combo_room_3.addItem("308");
            combo_room_3.addItem("309");

        } else if (combo_floor_3.getSelectedItem().toString().equals("4th")) {

            combo_room_3.removeAllItems();
            combo_room_3.addItem("401");
            combo_room_3.addItem("402");
            combo_room_3.addItem("403");

            combo_room_3.addItem("404");
            combo_room_3.addItem("405");
            combo_room_3.addItem("406");

            combo_room_3.addItem("407");
            combo_room_3.addItem("408");
            combo_room_3.addItem("409");

        } else if (combo_floor_3.getSelectedItem().toString().equals("5th")) {

            combo_room_3.removeAllItems();
            combo_room_3.addItem("501");
            combo_room_3.addItem("502");
            combo_room_3.addItem("503");

            combo_room_3.addItem("504");
            combo_room_3.addItem("505");
            combo_room_3.addItem("506");

            combo_room_3.addItem("507");
            combo_room_3.addItem("508");
            combo_room_3.addItem("509");
        }

    }//GEN-LAST:event_combo_floor_3ActionPerformed

    private void combo_floor_3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_floor_3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_floor_3PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecuirityForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_room;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_floor_1;
    private javax.swing.JComboBox<String> combo_floor_2;
    private javax.swing.JComboBox<String> combo_floor_3;
    private javax.swing.JComboBox<String> combo_question;
    private javax.swing.JComboBox<String> combo_room_1;
    private javax.swing.JComboBox<String> combo_room_2;
    private javax.swing.JComboBox<String> combo_room_3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_hallconnect1;
    private javax.swing.JLabel label_home21;
    private javax.swing.JLabel label_home22;
    private javax.swing.JLabel label_home23;
    private javax.swing.JLabel label_home24;
    private javax.swing.JLabel label_home25;
    private javax.swing.JLabel label_home26;
    private javax.swing.JLabel label_home27;
    private javax.swing.JLabel label_home6;
    private javax.swing.JLabel label_home7;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JTextField txt_answer;
    // End of variables declaration//GEN-END:variables
}
