/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SecuirityForm extends javax.swing.JFrame {

    private CentralController controller = new CentralController();

    private String name;
    private String reg;
    private int session;
    private String dob;
    private String blood;
    private String contact;
    private String email;
    private String username;
    private String pass;
    private String local_guardian_contact;
    private String local_guardian_relation;

    /**
     * Creates new form Registration
     */
    public SecuirityForm() {
        initComponents();
    }

    public SecuirityForm(CentralController controller, String name, String reg, int session, String dob, String blood, String contact, String email, String username, String pass, String local_guardian_contact, String local_guardian_relation) {
        this.controller = controller;
        this.name = name;
        this.reg = reg;
        this.session = session;
        this.dob = dob;
        this.blood = blood;
        this.contact = contact;
        this.email = email;
        this.username = username;
        this.pass = pass;
        this.local_guardian_contact = local_guardian_contact;
        this.local_guardian_relation = local_guardian_relation;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        txt_answer = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect1 = new javax.swing.JLabel();
        label_hallconnect = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_home4 = new javax.swing.JLabel();
        combo_question = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        label_home5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_answer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 500, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect1.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect1.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 140));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("ENTER SECURITY QUESTION AND ANSWER");
        panel_parent.add(label_hallconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 54));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 990, 10));

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("QUESTION :");
        panel_parent.add(label_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 170, 30));

        combo_question.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite pet's name?", "What is your favorite color?", "What is your favorite food?", "What is your favorite movie?", "What is your favorite book?", "What is your mother's maiden name?", "What city were you born in?", "What was your childhood nickname?" }));
        panel_parent.add(combo_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 500, 40));

        btn_submit.setBackground(new java.awt.Color(102, 102, 102));
        btn_submit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/signup.png"))); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 170, 54));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 140, 54));

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("ANSWER :");
        panel_parent.add(label_home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 150, 30));

        getContentPane().add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String question = combo_question.getSelectedItem().toString();
        String ans = txt_answer.getText();
        if (ans.equals("")) {
            JOptionPane.showMessageDialog(this, "PLEASE ENTER QUESTION AND ANSWER");
        } else {

            try {
                Connection con = DbConnection.getConnection();
                PreparedStatement pst = con.prepareStatement("INSERT INTO pending (name, reg, session, dob, blood, contact, email, username, pass, local_guardian_contact, local_guardian_relation, question, ans) "
                        + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

                pst.setString(1, name);
                pst.setString(2, reg);
                pst.setInt(3, session);
                pst.setString(4, dob);
                pst.setString(5, blood);
                pst.setString(6, contact);
                pst.setString(7, email);
                pst.setString(8, username);
                pst.setString(9, pass);
                pst.setString(10, local_guardian_contact);
                pst.setString(11, local_guardian_relation);
                pst.setString(12, question);
                pst.setString(13, ans);

// Execute the query
                int rowCount = pst.executeUpdate();

                if (rowCount > 0) {
                    JOptionPane.showMessageDialog(this, "SIGNUP SUCCESSFULL");
                    loginPage lg = new loginPage(controller);
                    lg.setVisible(true);
                    this.dispose();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "SIGNUP FAILED");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecuirityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecuirityForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_question;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_hallconnect1;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JTextField txt_answer;
    // End of variables declaration//GEN-END:variables
}
