/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SignUp extends javax.swing.JFrame {
   private CentralController controller = new CentralController();
    /**
     * Creates new form Registration
     */
    public SignUp(CentralController controller) {
        this.controller=controller;
        initComponents();
    }
    public SignUp() {
        initComponents();
    }
//    boolean usernameValidation(String username){
//       Connection con = DbConnection.getConnection();
//       
//    return false;
//    }
    boolean validUsername(String username){
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM student where username=?");
            pst.setString(1, username);
            ResultSet rs_1=pst.executeQuery();
             pst = con.prepareStatement("SELECT * FROM pending where username=?");
            pst.setString(1, username);
            ResultSet rs_2=pst.executeQuery();
            if(rs_1.next() || rs_2.next()){
               JOptionPane.showMessageDialog(this, "THIS USERNAME HAS TAKEN, PLEASE USE AN UNIQUE USERNAME");
                return false;
            }else{
             return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }
      boolean validation(String name,String reg,int session,String dob,String blood,String contact,String email,String username,String pass,String con_pass){
          if(name.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER NAME");
              return false;
          }
          if(reg.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER REGISTRATION NUMBER");
              return false;
          }
          if(session==0){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER SESSION");
              return false;
          }
          if(dob.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER DATE OF BIRTH");
              return false;
          }
          if(blood.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER BLOOD GROUP");
              return false;
          }
          if(contact.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER CONTACT NUMBER");
              return false;
          }
          if(email.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER EMAIL");
              return false;
          }
          if(username.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER USERNAME");
              return false;
          }
          
          if(pass.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER PASSWORD");
              return false;
          }
          if(con_pass.equals("")){
              JOptionPane.showMessageDialog(this, "PLEASE ENTER CONFIRM PASSWORD");
              return false;
          }
          if(!pass.equals(con_pass)){
            JOptionPane.showMessageDialog(this, "PASSWORD DOES NOT MATCHED");
            return false;
          }
          validUsername(username);
      return true;
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        label_signup = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_parent1 = new javax.swing.JPanel();
        label_signup1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        label_hallconnect1 = new javax.swing.JLabel();
        label_home7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label_home8 = new javax.swing.JLabel();
        label_home9 = new javax.swing.JLabel();
        label_home5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        label_home6 = new javax.swing.JLabel();
        txt_reg = new javax.swing.JTextField();
        label_home4 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_ConPass = new javax.swing.JPasswordField();
        label_home10 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        label_home11 = new javax.swing.JLabel();
        label_home12 = new javax.swing.JLabel();
        combo_blood = new javax.swing.JComboBox<>();
        label_home13 = new javax.swing.JLabel();
        txt_localGuardianContact = new javax.swing.JTextField();
        label_home14 = new javax.swing.JLabel();
        txt_localGuardianRelation = new javax.swing.JTextField();
        label_home15 = new javax.swing.JLabel();
        label_home16 = new javax.swing.JLabel();
        label_home17 = new javax.swing.JLabel();
        txt_dob = new com.toedter.calendar.JDateChooser();
        label_home18 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_session = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_signup.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_signup.setForeground(new java.awt.Color(255, 255, 255));
        label_signup.setText("SignUp");
        panel_parent.add(label_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 160, 50));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(623, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        panel_parent1.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent1.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent1.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_signup1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_signup1.setForeground(new java.awt.Color(255, 255, 255));
        label_signup1.setText("SignUp");
        panel_parent1.add(label_signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 160, 50));

        txt_username.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 280, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect1.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect1.setText("HallConnect");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_parent1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        label_home7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home7.setForeground(new java.awt.Color(255, 255, 255));
        label_home7.setText("BLOOD  :");
        panel_parent1.add(label_home7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, 30));
        panel_parent1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_home8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home8.setForeground(new java.awt.Color(255, 255, 255));
        label_home8.setText("USERNAME :");
        panel_parent1.add(label_home8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, 30));

        label_home9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home9.setForeground(new java.awt.Color(255, 255, 255));
        label_home9.setText("PASS :");
        panel_parent1.add(label_home9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, 30));

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("DATE OF BIRTH :");
        panel_parent1.add(label_home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 30));

        txt_name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 280, 40));

        label_home6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home6.setForeground(new java.awt.Color(255, 255, 255));
        label_home6.setText("REG :");
        panel_parent1.add(label_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, 30));

        txt_reg.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 280, 40));

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("SESSION :");
        panel_parent1.add(label_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, -1, 30));

        txt_pass.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        panel_parent1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 280, 40));

        txt_ConPass.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        panel_parent1.add(txt_ConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, 280, 40));

        label_home10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home10.setForeground(new java.awt.Color(255, 255, 255));
        label_home10.setText("CONTACT NO :");
        panel_parent1.add(label_home10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 30));

        txt_contact.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 280, 40));

        txt_email.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 280, 40));

        label_home11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home11.setForeground(new java.awt.Color(255, 255, 255));
        label_home11.setText("E-MAIL :");
        panel_parent1.add(label_home11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 30));

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("CONFIRM PASS :");
        panel_parent1.add(label_home12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, 30));

        combo_blood.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        panel_parent1.add(combo_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 280, 40));

        label_home13.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home13.setForeground(new java.awt.Color(0, 255, 102));
        label_home13.setText("(EXAMPLE: 2021-2022)");
        panel_parent1.add(label_home13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, -1, 30));

        txt_localGuardianContact.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_localGuardianContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 280, 40));

        label_home14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home14.setForeground(new java.awt.Color(255, 255, 255));
        label_home14.setText("RELATION WITH LOCAL GUARDIAN :");
        panel_parent1.add(label_home14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, -1, 30));

        txt_localGuardianRelation.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_localGuardianRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_localGuardianRelationActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_localGuardianRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 530, 280, 40));

        label_home15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home15.setForeground(new java.awt.Color(255, 255, 255));
        label_home15.setText("LOCAL GUARDIAN CONTACT NO :");
        panel_parent1.add(label_home15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, 30));

        label_home16.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home16.setForeground(new java.awt.Color(0, 255, 102));
        label_home16.setText("(OPTIONAL)");
        panel_parent1.add(label_home16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, 30));

        label_home17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home17.setForeground(new java.awt.Color(255, 255, 255));
        label_home17.setText("NAME :");
        panel_parent1.add(label_home17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        txt_dob.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 280, 40));

        label_home18.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home18.setForeground(new java.awt.Color(0, 255, 102));
        label_home18.setText("(OPTIONAL)");
        panel_parent1.add(label_home18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 580, -1, 30));

        btn_login.setBackground(new java.awt.Color(102, 102, 102));
        btn_login.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/login.png"))); // NOI18N
        btn_login.setText("LOG IN");
        btn_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        panel_parent1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 150, 54));

        btn_signup.setBackground(new java.awt.Color(102, 102, 102));
        btn_signup.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/signup.png"))); // NOI18N
        btn_signup.setText("SUBMIT");
        btn_signup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        panel_parent1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 170, 54));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 140, 54));

        txt_session.setMinimum(0);
        txt_session.setValue(0);
        panel_parent1.add(txt_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 100, 40));

        panel_parent.add(panel_parent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 800));

        getContentPane().add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_localGuardianRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_localGuardianRelationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localGuardianRelationActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        controller.addFrame(this);
        this.setVisible(false);
        loginPage lg = new loginPage(controller);
        lg.setVisible(true);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formate = new SimpleDateFormat("dd-MM-yyyy");
           String name = txt_name.getText();
           String reg = txt_reg.getText();
           int session = txt_session.getYear();
           Date db = txt_dob.getDate();
            String dob="";
           if(db!=null){
              dob = formate.format(txt_dob.getDate());
           }

           String blood=combo_blood.getSelectedItem().toString();
           String contact = txt_contact.getText();
           String email = txt_email.getText();
           String username = txt_username.getText();
           String pass = txt_pass.getText();
           String con_pass = txt_ConPass.getText();
           String local_guardian_contact=txt_localGuardianContact.getText();
           String local_guardian_relation=txt_localGuardianRelation.getText();
        if(validation(name, reg, session, dob, blood, contact, email, username, pass, con_pass)){
          controller.addFrame(this);
          SecuirityForm sf = new SecuirityForm(controller,name, reg, session, dob, blood, contact, email, username, pass,local_guardian_contact,local_guardian_relation);
          sf.setVisible(true);
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JComboBox<String> combo_blood;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_hallconnect1;
    private javax.swing.JLabel label_home10;
    private javax.swing.JLabel label_home11;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home14;
    private javax.swing.JLabel label_home15;
    private javax.swing.JLabel label_home16;
    private javax.swing.JLabel label_home17;
    private javax.swing.JLabel label_home18;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JLabel label_home6;
    private javax.swing.JLabel label_home7;
    private javax.swing.JLabel label_home8;
    private javax.swing.JLabel label_home9;
    private javax.swing.JLabel label_signup;
    private javax.swing.JLabel label_signup1;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_parent1;
    private javax.swing.JPasswordField txt_ConPass;
    private javax.swing.JTextField txt_contact;
    private com.toedter.calendar.JDateChooser txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_localGuardianContact;
    private javax.swing.JTextField txt_localGuardianRelation;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_reg;
    private com.toedter.calendar.JYearChooser txt_session;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
