/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect;

/**
 *
 * @author Lenovo
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        btn_home3 = new javax.swing.JButton();
        label_signup = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_parent1 = new javax.swing.JPanel();
        btn_home4 = new javax.swing.JButton();
        label_signup1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        label_hallconnect1 = new javax.swing.JLabel();
        label_home7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label_home8 = new javax.swing.JLabel();
        label_home9 = new javax.swing.JLabel();
        label_home5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        label_home6 = new javax.swing.JLabel();
        txt_reg = new javax.swing.JTextField();
        label_home4 = new javax.swing.JLabel();
        txt_session = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_ConPass = new javax.swing.JPasswordField();
        label_home10 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        label_home11 = new javax.swing.JLabel();
        label_home12 = new javax.swing.JLabel();
        combo_blood = new javax.swing.JComboBox<>();
        label_home13 = new javax.swing.JLabel();
        txt_localGuardianContact = new javax.swing.JTextField();
        label_home14 = new javax.swing.JLabel();
        txt_localGuardianRelation = new javax.swing.JTextField();
        label_home15 = new javax.swing.JLabel();
        label_home16 = new javax.swing.JLabel();
        label_home17 = new javax.swing.JLabel();
        txt_dob = new com.toedter.calendar.JDateChooser();
        label_home18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home3.setBackground(new java.awt.Color(102, 102, 102));
        btn_home3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_home3.setForeground(new java.awt.Color(255, 255, 255));
        btn_home3.setText("HOME");
        btn_home3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home3ActionPerformed(evt);
            }
        });
        panel_parent.add(btn_home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 131, 54));

        label_signup.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_signup.setForeground(new java.awt.Color(255, 255, 255));
        label_signup.setText("SignUp");
        panel_parent.add(label_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 160, 50));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        panel_parent1.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent1.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent1.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home4.setBackground(new java.awt.Color(102, 102, 102));
        btn_home4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_home4.setForeground(new java.awt.Color(255, 255, 255));
        btn_home4.setText("HOME");
        btn_home4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_home4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home4ActionPerformed(evt);
            }
        });
        panel_parent1.add(btn_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 131, 54));

        label_signup1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_signup1.setForeground(new java.awt.Color(255, 255, 255));
        label_signup1.setText("SignUp");
        panel_parent1.add(label_signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 160, 50));

        txt_username.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 280, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect1.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect1.setText("HallConnect");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_hallconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_parent1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        label_home7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home7.setForeground(new java.awt.Color(255, 255, 255));
        label_home7.setText("BLOOD  :");
        panel_parent1.add(label_home7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, 30));
        panel_parent1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_home8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home8.setForeground(new java.awt.Color(255, 255, 255));
        label_home8.setText("USERNAME :");
        panel_parent1.add(label_home8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, 30));

        label_home9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home9.setForeground(new java.awt.Color(255, 255, 255));
        label_home9.setText("PASS :");
        panel_parent1.add(label_home9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, 30));

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("DATE OF BIRTH :");
        panel_parent1.add(label_home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 30));

        txt_name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 280, 40));

        label_home6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home6.setForeground(new java.awt.Color(255, 255, 255));
        label_home6.setText("REG :");
        panel_parent1.add(label_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, 30));

        txt_reg.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 280, 40));

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("SESSION :");
        panel_parent1.add(label_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, -1, 30));

        txt_session.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sessionActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 280, 40));

        txt_pass.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        panel_parent1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 280, 40));

        txt_ConPass.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        panel_parent1.add(txt_ConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, 280, 40));

        label_home10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home10.setForeground(new java.awt.Color(255, 255, 255));
        label_home10.setText("CONTACT NO :");
        panel_parent1.add(label_home10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 30));

        txt_contact.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 280, 40));

        txt_email.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 280, 40));

        label_home11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home11.setForeground(new java.awt.Color(255, 255, 255));
        label_home11.setText("E-MAIL :");
        panel_parent1.add(label_home11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 30));

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("CONFIRM PASS :");
        panel_parent1.add(label_home12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, 30));

        combo_blood.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        panel_parent1.add(combo_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 280, 40));

        label_home13.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home13.setForeground(new java.awt.Color(0, 255, 102));
        label_home13.setText("(EXAMPLE: 2021-2022)");
        panel_parent1.add(label_home13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 290, -1, 30));

        txt_localGuardianContact.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_localGuardianContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 280, 40));

        label_home14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home14.setForeground(new java.awt.Color(255, 255, 255));
        label_home14.setText("RELATION WITH LOCAL GUARDIAN :");
        panel_parent1.add(label_home14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, -1, 30));

        txt_localGuardianRelation.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_localGuardianRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_localGuardianRelationActionPerformed(evt);
            }
        });
        panel_parent1.add(txt_localGuardianRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 530, 280, 40));

        label_home15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home15.setForeground(new java.awt.Color(255, 255, 255));
        label_home15.setText("LOCAL GUARDIAN CONTACT NO :");
        panel_parent1.add(label_home15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, 30));

        label_home16.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home16.setForeground(new java.awt.Color(0, 255, 102));
        label_home16.setText("(OPTIONAL)");
        panel_parent1.add(label_home16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, 30));

        label_home17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home17.setForeground(new java.awt.Color(255, 255, 255));
        label_home17.setText("NAME :");
        panel_parent1.add(label_home17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        txt_dob.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panel_parent1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 280, 40));

        label_home18.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        label_home18.setForeground(new java.awt.Color(0, 255, 102));
        label_home18.setText("(OPTIONAL)");
        panel_parent1.add(label_home18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 580, -1, 30));

        panel_parent.add(panel_parent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 800));

        getContentPane().add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_home3ActionPerformed

    private void txt_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regActionPerformed

    private void txt_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sessionActionPerformed

    private void btn_home4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_home4ActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_localGuardianRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_localGuardianRelationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localGuardianRelationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home3;
    private javax.swing.JButton btn_home4;
    private javax.swing.JComboBox<String> combo_blood;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_hallconnect1;
    private javax.swing.JLabel label_home10;
    private javax.swing.JLabel label_home11;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home14;
    private javax.swing.JLabel label_home15;
    private javax.swing.JLabel label_home16;
    private javax.swing.JLabel label_home17;
    private javax.swing.JLabel label_home18;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JLabel label_home6;
    private javax.swing.JLabel label_home7;
    private javax.swing.JLabel label_home8;
    private javax.swing.JLabel label_home9;
    private javax.swing.JLabel label_signup;
    private javax.swing.JLabel label_signup1;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_parent1;
    private javax.swing.JPasswordField txt_ConPass;
    private javax.swing.JTextField txt_contact;
    private com.toedter.calendar.JDateChooser txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_localGuardianContact;
    private javax.swing.JTextField txt_localGuardianRelation;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_reg;
    private javax.swing.JTextField txt_session;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
