/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class StudentDashboard extends javax.swing.JFrame {
  private CentralController controller = new CentralController();
    /**
     * Creates new form loginPage
     */
    public StudentDashboard(CentralController controller) {
        this.controller=controller;
        initComponents();
    }
    public StudentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_welcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label_home18 = new javax.swing.JLabel();
        label_home19 = new javax.swing.JLabel();
        label_home20 = new javax.swing.JLabel();
        label_home21 = new javax.swing.JLabel();
        label_home22 = new javax.swing.JLabel();
        label_home23 = new javax.swing.JLabel();
        panel_clearence = new javax.swing.JPanel();
        label_home2 = new javax.swing.JLabel();
        label_home3 = new javax.swing.JLabel();
        panel_fee = new javax.swing.JPanel();
        label_home4 = new javax.swing.JLabel();
        label_home5 = new javax.swing.JLabel();
        panel_room = new javax.swing.JPanel();
        label_home6 = new javax.swing.JLabel();
        panel_notice = new javax.swing.JPanel();
        label_home8 = new javax.swing.JLabel();
        label_home9 = new javax.swing.JLabel();
        panel_complain = new javax.swing.JPanel();
        label_home10 = new javax.swing.JLabel();
        panel_associates = new javax.swing.JPanel();
        label_home12 = new javax.swing.JLabel();
        label_home13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_welcome.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_welcome.setForeground(new java.awt.Color(255, 255, 255));
        label_welcome.setText("Welcome");
        panel_parent.add(label_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 190, 50));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home18.setForeground(new java.awt.Color(255, 255, 255));
        label_home18.setText("Name           :");
        jPanel2.add(label_home18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        label_home19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home19.setForeground(new java.awt.Color(255, 255, 255));
        label_home19.setText("Reg no.        :");
        jPanel2.add(label_home19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        label_home20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home20.setForeground(new java.awt.Color(255, 255, 255));
        label_home20.setText("Session        :");
        jPanel2.add(label_home20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        label_home21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home21.setForeground(new java.awt.Color(255, 255, 255));
        label_home21.setText("Contact no.  :");
        jPanel2.add(label_home21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        label_home22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home22.setForeground(new java.awt.Color(255, 255, 255));
        label_home22.setText("E-mail           :");
        jPanel2.add(label_home22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        label_home23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home23.setForeground(new java.awt.Color(255, 255, 255));
        label_home23.setText("Blood            :");
        jPanel2.add(label_home23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        panel_parent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 670, 320));

        panel_clearence.setBackground(new java.awt.Color(153, 0, 51));
        panel_clearence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_clearence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_clearenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_clearenceMouseExited(evt);
            }
        });

        label_home2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home2.setForeground(new java.awt.Color(255, 255, 255));
        label_home2.setText("Clearnece");

        label_home3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home3.setForeground(new java.awt.Color(255, 255, 255));
        label_home3.setText("Application");

        javax.swing.GroupLayout panel_clearenceLayout = new javax.swing.GroupLayout(panel_clearence);
        panel_clearence.setLayout(panel_clearenceLayout);
        panel_clearenceLayout.setHorizontalGroup(
            panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clearenceLayout.createSequentialGroup()
                .addGroup(panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clearenceLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(label_home2))
                    .addGroup(panel_clearenceLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label_home3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_clearenceLayout.setVerticalGroup(
            panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clearenceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_home2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_home3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_parent.add(panel_clearence, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 210, 120));

        panel_fee.setBackground(new java.awt.Color(153, 0, 51));
        panel_fee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_feeMouseExited(evt);
            }
        });

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("Hall Fee");

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("Payment");

        javax.swing.GroupLayout panel_feeLayout = new javax.swing.GroupLayout(panel_fee);
        panel_fee.setLayout(panel_feeLayout);
        panel_feeLayout.setHorizontalGroup(
            panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_home4)
                    .addComponent(label_home5))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panel_feeLayout.setVerticalGroup(
            panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_home4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_parent.add(panel_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, 120));

        panel_room.setBackground(new java.awt.Color(153, 0, 51));
        panel_room.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_roomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_roomMouseExited(evt);
            }
        });

        label_home6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home6.setForeground(new java.awt.Color(255, 255, 255));
        label_home6.setText("Room");

        javax.swing.GroupLayout panel_roomLayout = new javax.swing.GroupLayout(panel_room);
        panel_room.setLayout(panel_roomLayout);
        panel_roomLayout.setHorizontalGroup(
            panel_roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_roomLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(label_home6)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panel_roomLayout.setVerticalGroup(
            panel_roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_roomLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(label_home6)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panel_parent.add(panel_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 210, 120));

        panel_notice.setBackground(new java.awt.Color(153, 0, 51));
        panel_notice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_notice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_noticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_noticeMouseExited(evt);
            }
        });

        label_home8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home8.setForeground(new java.awt.Color(255, 255, 255));
        label_home8.setText("Notice");

        label_home9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home9.setForeground(new java.awt.Color(255, 255, 255));
        label_home9.setText("Board");

        javax.swing.GroupLayout panel_noticeLayout = new javax.swing.GroupLayout(panel_notice);
        panel_notice.setLayout(panel_noticeLayout);
        panel_noticeLayout.setHorizontalGroup(
            panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_noticeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_home8)
                    .addComponent(label_home9))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panel_noticeLayout.setVerticalGroup(
            panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_noticeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_home8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home9)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_parent.add(panel_notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 210, 120));

        panel_complain.setBackground(new java.awt.Color(153, 0, 51));
        panel_complain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_complain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_complainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_complainMouseExited(evt);
            }
        });

        label_home10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home10.setForeground(new java.awt.Color(255, 255, 255));
        label_home10.setText("Complain");

        javax.swing.GroupLayout panel_complainLayout = new javax.swing.GroupLayout(panel_complain);
        panel_complain.setLayout(panel_complainLayout);
        panel_complainLayout.setHorizontalGroup(
            panel_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_complainLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(label_home10)
                .addGap(39, 39, 39))
        );
        panel_complainLayout.setVerticalGroup(
            panel_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_complainLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(label_home10)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panel_parent.add(panel_complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 210, 120));

        panel_associates.setBackground(new java.awt.Color(153, 0, 51));
        panel_associates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_associates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_associatesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_associatesMouseExited(evt);
            }
        });

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("Hall");

        label_home13.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home13.setForeground(new java.awt.Color(255, 255, 255));
        label_home13.setText("Associates");

        javax.swing.GroupLayout panel_associatesLayout = new javax.swing.GroupLayout(panel_associates);
        panel_associates.setLayout(panel_associatesLayout);
        panel_associatesLayout.setHorizontalGroup(
            panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_associatesLayout.createSequentialGroup()
                .addGroup(panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_associatesLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(label_home12))
                    .addGroup(panel_associatesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(label_home13)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel_associatesLayout.setVerticalGroup(
            panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_associatesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_home12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home13)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_parent.add(panel_associates, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 210, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_feeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_fee.setBackground(clr);
    }//GEN-LAST:event_panel_feeMouseEntered

    private void panel_roomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_roomMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_room.setBackground(clr);
    }//GEN-LAST:event_panel_roomMouseEntered

    private void panel_noticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_noticeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_notice.setBackground(clr);
    }//GEN-LAST:event_panel_noticeMouseEntered

    private void panel_complainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_complain.setBackground(clr);
    }//GEN-LAST:event_panel_complainMouseEntered

    private void panel_associatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_associatesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_associates.setBackground(clr);
    }//GEN-LAST:event_panel_associatesMouseEntered

    private void panel_clearenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearenceMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_clearence.setBackground(clr);
    }//GEN-LAST:event_panel_clearenceMouseEntered

    private void panel_feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_feeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_fee.setBackground(clr);
    }//GEN-LAST:event_panel_feeMouseExited

    private void panel_roomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_roomMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_room.setBackground(clr);
    }//GEN-LAST:event_panel_roomMouseExited

    private void panel_noticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_noticeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_notice.setBackground(clr);
    }//GEN-LAST:event_panel_noticeMouseExited

    private void panel_complainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_complain.setBackground(clr);
    }//GEN-LAST:event_panel_complainMouseExited

    private void panel_associatesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_associatesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_associates.setBackground(clr);
    }//GEN-LAST:event_panel_associatesMouseExited

    private void panel_clearenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearenceMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_clearence.setBackground(clr);
    }//GEN-LAST:event_panel_clearenceMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_home10;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home18;
    private javax.swing.JLabel label_home19;
    private javax.swing.JLabel label_home2;
    private javax.swing.JLabel label_home20;
    private javax.swing.JLabel label_home21;
    private javax.swing.JLabel label_home22;
    private javax.swing.JLabel label_home23;
    private javax.swing.JLabel label_home3;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JLabel label_home6;
    private javax.swing.JLabel label_home8;
    private javax.swing.JLabel label_home9;
    private javax.swing.JLabel label_welcome;
    private javax.swing.JPanel panel_associates;
    private javax.swing.JPanel panel_clearence;
    private javax.swing.JPanel panel_complain;
    private javax.swing.JPanel panel_fee;
    private javax.swing.JPanel panel_notice;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_room;
    // End of variables declaration//GEN-END:variables
}
