/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.room;

import hallconnect.database.CentralController;
import hallconnect.provost.provostDashboard;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class RoomSelection extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    private String hall;

    /**
     * Creates new form loginPage
     */
    public RoomSelection(CentralController controller,String hall) {
        this.hall=hall;
        this.controller = controller;
        initComponents();
        fillinfo(hall);
    }

    public RoomSelection() {
        initComponents();
        
    }
    void fillinfo(String hall){
        label_hallName.setText(hall);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_hallName = new javax.swing.JLabel();
        panel_second = new javax.swing.JPanel();
        label_home12 = new javax.swing.JLabel();
        label_home14 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_first = new javax.swing.JPanel();
        label_home13 = new javax.swing.JLabel();
        label_home27 = new javax.swing.JLabel();
        panel_third = new javax.swing.JPanel();
        label_home28 = new javax.swing.JLabel();
        label_home29 = new javax.swing.JLabel();
        panel_fifth = new javax.swing.JPanel();
        label_home30 = new javax.swing.JLabel();
        label_home31 = new javax.swing.JLabel();
        panel_fourth = new javax.swing.JPanel();
        label_home32 = new javax.swing.JLabel();
        label_home33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 140, 60));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_hallName.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_hallName.setForeground(new java.awt.Color(255, 255, 255));
        label_hallName.setText("BANGABANDHU HALL");
        panel_parent.add(label_hallName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 480, 50));

        panel_second.setBackground(new java.awt.Color(0, 51, 51));
        panel_second.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_secondMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_secondMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_secondMouseExited(evt);
            }
        });
        panel_second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("Floor");
        panel_second.add(label_home12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 50));

        label_home14.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home14.setForeground(new java.awt.Color(255, 255, 255));
        label_home14.setText("Second");
        panel_second.add(label_home14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        panel_parent.add(panel_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 210, 220));

        btn_exit.setBackground(new java.awt.Color(102, 102, 102));
        btn_exit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/exit.png"))); // NOI18N
        btn_exit.setText(" EXIT");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 160, 60));

        panel_first.setBackground(new java.awt.Color(0, 51, 51));
        panel_first.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_firstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_firstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_firstMouseExited(evt);
            }
        });
        panel_first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home13.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home13.setForeground(new java.awt.Color(255, 255, 255));
        label_home13.setText("Floor");
        panel_first.add(label_home13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 50));

        label_home27.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home27.setForeground(new java.awt.Color(255, 255, 255));
        label_home27.setText("First");
        panel_first.add(label_home27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        panel_parent.add(panel_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 210, 220));

        panel_third.setBackground(new java.awt.Color(0, 51, 51));
        panel_third.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_third.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_thirdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_thirdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_thirdMouseExited(evt);
            }
        });
        panel_third.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home28.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home28.setForeground(new java.awt.Color(255, 255, 255));
        label_home28.setText("Floor");
        panel_third.add(label_home28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 50));

        label_home29.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home29.setForeground(new java.awt.Color(255, 255, 255));
        label_home29.setText("Third");
        panel_third.add(label_home29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        panel_parent.add(panel_third, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 210, 220));

        panel_fifth.setBackground(new java.awt.Color(0, 51, 51));
        panel_fifth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_fifth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fifthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_fifthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_fifthMouseExited(evt);
            }
        });
        panel_fifth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home30.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home30.setForeground(new java.awt.Color(255, 255, 255));
        label_home30.setText("Floor");
        panel_fifth.add(label_home30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 50));

        label_home31.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home31.setForeground(new java.awt.Color(255, 255, 255));
        label_home31.setText("Fifth");
        panel_fifth.add(label_home31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        panel_parent.add(panel_fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 330, 210, 220));

        panel_fourth.setBackground(new java.awt.Color(0, 51, 51));
        panel_fourth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_fourth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fourthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_fourthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_fourthMouseExited(evt);
            }
        });
        panel_fourth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home32.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home32.setForeground(new java.awt.Color(255, 255, 255));
        label_home32.setText("Floor");
        panel_fourth.add(label_home32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 50));

        label_home33.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_home33.setForeground(new java.awt.Color(255, 255, 255));
        label_home33.setText("Fourth");
        panel_fourth.add(label_home33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        panel_parent.add(panel_fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 210, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void panel_secondMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_second.setBackground(clr);
    }//GEN-LAST:event_panel_secondMouseEntered

    private void panel_secondMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_second.setBackground(clr);
    }//GEN-LAST:event_panel_secondMouseExited

    private void panel_firstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_first.setBackground(clr);
    }//GEN-LAST:event_panel_firstMouseEntered

    private void panel_firstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_first.setBackground(clr);
    }//GEN-LAST:event_panel_firstMouseExited

    private void panel_thirdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_third.setBackground(clr);
    }//GEN-LAST:event_panel_thirdMouseEntered

    private void panel_thirdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_third.setBackground(clr);
    }//GEN-LAST:event_panel_thirdMouseExited

    private void panel_fifthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_fifth.setBackground(clr);
    }//GEN-LAST:event_panel_fifthMouseEntered

    private void panel_fifthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_fifth.setBackground(clr);
    }//GEN-LAST:event_panel_fifthMouseExited

    private void panel_fourthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_fourth.setBackground(clr);
    }//GEN-LAST:event_panel_fourthMouseEntered

    private void panel_fourthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_fourth.setBackground(clr);
    }//GEN-LAST:event_panel_fourthMouseExited

    private void panel_firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        FirstFloor fst = new FirstFloor(controller,hall);
        fst.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_panel_firstMouseClicked

    private void panel_secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseClicked
        // TODO add your handling code here:
        
        controller.addFrame(this);
        SecondFloor fst = new SecondFloor(controller,hall);
        fst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_secondMouseClicked

    private void panel_thirdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        ThirdFloor fst = new ThirdFloor(controller,hall);
        fst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_thirdMouseClicked

    private void panel_fourthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        FourthFloor fst = new FourthFloor(controller,hall);
        fst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_fourthMouseClicked

    private void panel_fifthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        FifthFloor fst = new FifthFloor(controller,hall);
        fst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_fifthMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_hallName;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home14;
    private javax.swing.JLabel label_home27;
    private javax.swing.JLabel label_home28;
    private javax.swing.JLabel label_home29;
    private javax.swing.JLabel label_home30;
    private javax.swing.JLabel label_home31;
    private javax.swing.JLabel label_home32;
    private javax.swing.JLabel label_home33;
    private javax.swing.JPanel panel_fifth;
    private javax.swing.JPanel panel_first;
    private javax.swing.JPanel panel_fourth;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_second;
    private javax.swing.JPanel panel_third;
    // End of variables declaration//GEN-END:variables
}
