/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.room;

import hallconnect.database.*;
import hallconnect.provost.provostDashboard;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Arrays;

/**
 *
 * @author Lenovo
 */
public class RoomDetails extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    private String hall;
    private int room_count = 0;
    private String room_no;

    /**
     * Creates new form loginPage
     */
    public RoomDetails(CentralController controller, String hall, int room_count, String room_no) {
        this.hall = hall;
        this.controller = controller;
        this.room_count = room_count;
        this.room_no = room_no;
        initComponents();
        fillinfo1(hall);
        fillInfo(room_no);
    }

    public RoomDetails() {
        initComponents();
        fillInfo(room_no);
        fillinfo1(hall);

    }

    void fillinfo1(String hall) {
        label_hallName.setText(hall);
        if (room_count == 4) {
            panel_second.setVisible(false);
            panel_fifth.setVisible(false);
        }
    }

    void fillInfo(String roomNo) {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(
                    "SELECT username, dept FROM room_details WHERE hall_name = ? AND room_no = ?"
            );
            pst.setString(1, hall); // Assuming `hall` is a global variable
            pst.setString(2, roomNo);

            ResultSet rs = pst.executeQuery();

            // Assuming you have labels like label_user_1, label_user_2, etc.
            List<JLabel> userLabels;
            List<JLabel> deptLabels;
             
            if(room_count==6){
            userLabels = Arrays.asList(label_name_first,label_name_second,label_name_third,label_name_fourth,label_name_fifth,label_name_sixth);
            deptLabels = Arrays.asList(label_dept_first,label_dept_second,label_dept_third,label_dept_fourth,label_dept_fifth,label_dept_sixth);
            }else{
            userLabels = Arrays.asList(label_name_first,label_name_third,label_name_fourth,label_name_sixth);
            deptLabels = Arrays.asList(label_dept_first,label_dept_third,label_dept_fourth,label_dept_sixth);
            }

            int index = 0;
            while (rs.next() && index < userLabels.size()) {
                userLabels.get(index).setText(rs.getString("username"));
                deptLabels.get(index).setText(rs.getString("dept"));
                index++;
            }

            // Clear remaining labels if there are fewer than 4 occupants
            while (index < userLabels.size()) {
                userLabels.get(index).setText("");
                deptLabels.get(index).setText("");
                index++;
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace(); // Debugging in case of an error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_hallName = new javax.swing.JLabel();
        panel_second = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        label_name_second = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_dept_second = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_third = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label_name_third = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_dept_third = new javax.swing.JLabel();
        panel_first = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_dept_first = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_name_first = new javax.swing.JLabel();
        panel_sixth = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        label_name_sixth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_dept_sixth = new javax.swing.JLabel();
        panel_fifth = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        label_name_fifth = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_dept_fifth = new javax.swing.JLabel();
        panel_fourth = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        label_name_fourth = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_dept_fourth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 140, 60));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_hallName.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_hallName.setForeground(new java.awt.Color(255, 255, 255));
        label_hallName.setText("BANGABANDHU HALL");
        panel_parent.add(label_hallName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 480, 50));

        panel_second.setBackground(new java.awt.Color(0, 51, 51));
        panel_second.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_secondMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_secondMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_secondMouseExited(evt);
            }
        });
        panel_second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME:");
        panel_second.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_second.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_second.setForeground(new java.awt.Color(255, 255, 255));
        panel_second.add(label_name_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEPARTMENT:");
        panel_second.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_second.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_second.setForeground(new java.awt.Color(255, 255, 255));
        panel_second.add(label_dept_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        panel_parent.add(panel_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 360, 160));

        btn_exit.setBackground(new java.awt.Color(102, 102, 102));
        btn_exit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/exit.png"))); // NOI18N
        btn_exit.setText(" EXIT");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 160, 60));

        panel_third.setBackground(new java.awt.Color(0, 51, 51));
        panel_third.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_third.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_thirdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_thirdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_thirdMouseExited(evt);
            }
        });
        panel_third.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME:");
        panel_third.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_third.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_third.setForeground(new java.awt.Color(255, 255, 255));
        panel_third.add(label_name_third, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEPARTMENT:");
        panel_third.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_third.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_third.setForeground(new java.awt.Color(255, 255, 255));
        panel_third.add(label_dept_third, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        panel_parent.add(panel_third, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 360, 160));

        panel_first.setBackground(new java.awt.Color(0, 51, 51));
        panel_first.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_firstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_firstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_firstMouseExited(evt);
            }
        });
        panel_first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEPARTMENT:");
        panel_first.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_first.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_first.setForeground(new java.awt.Color(255, 255, 255));
        panel_first.add(label_dept_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME:");
        panel_first.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_first.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_first.setForeground(new java.awt.Color(255, 255, 255));
        panel_first.add(label_name_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        panel_parent.add(panel_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 360, 160));

        panel_sixth.setBackground(new java.awt.Color(0, 51, 51));
        panel_sixth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_sixth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_sixthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_sixthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_sixthMouseExited(evt);
            }
        });
        panel_sixth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAME:");
        panel_sixth.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_sixth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_sixth.setForeground(new java.awt.Color(255, 255, 255));
        panel_sixth.add(label_name_sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DEPARTMENT:");
        panel_sixth.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_sixth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_sixth.setForeground(new java.awt.Color(255, 255, 255));
        panel_sixth.add(label_dept_sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        panel_parent.add(panel_sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 610, 360, 160));

        panel_fifth.setBackground(new java.awt.Color(0, 51, 51));
        panel_fifth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_fifth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fifthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_fifthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_fifthMouseExited(evt);
            }
        });
        panel_fifth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAME:");
        panel_fifth.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_fifth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_fifth.setForeground(new java.awt.Color(255, 255, 255));
        panel_fifth.add(label_name_fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DEPARTMENT:");
        panel_fifth.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_fifth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_fifth.setForeground(new java.awt.Color(255, 255, 255));
        panel_fifth.add(label_dept_fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        panel_parent.add(panel_fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, 360, 160));

        panel_fourth.setBackground(new java.awt.Color(0, 51, 51));
        panel_fourth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_fourth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fourthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_fourthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_fourthMouseExited(evt);
            }
        });
        panel_fourth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NAME:");
        panel_fourth.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 30));

        label_name_fourth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_name_fourth.setForeground(new java.awt.Color(255, 255, 255));
        panel_fourth.add(label_name_fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DEPARTMENT:");
        panel_fourth.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        label_dept_fourth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        label_dept_fourth.setForeground(new java.awt.Color(255, 255, 255));
        panel_fourth.add(label_dept_fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        panel_parent.add(panel_fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 360, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void panel_secondMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_second.setBackground(clr);
    }//GEN-LAST:event_panel_secondMouseEntered

    private void panel_secondMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 51, 51);
        panel_second.setBackground(clr);
    }//GEN-LAST:event_panel_secondMouseExited

    private void panel_thirdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_third.setBackground(clr);
    }//GEN-LAST:event_panel_thirdMouseEntered

    private void panel_thirdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 51, 51);
        panel_third.setBackground(clr);
    }//GEN-LAST:event_panel_thirdMouseExited

    private void panel_thirdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_thirdMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        FirstFloor fst = new FirstFloor(controller, hall);
        fst.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_panel_thirdMouseClicked

    private void panel_secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_secondMouseClicked
        // TODO add your handling code here:

        controller.addFrame(this);
        SecondFloor fst = new SecondFloor(controller, hall);
        fst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_secondMouseClicked

    private void panel_firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_firstMouseClicked

    private void panel_firstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_firstMouseEntered

    private void panel_firstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_firstMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_firstMouseExited

    private void panel_sixthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sixthMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sixthMouseClicked

    private void panel_sixthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sixthMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sixthMouseEntered

    private void panel_sixthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sixthMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sixthMouseExited

    private void panel_fifthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fifthMouseClicked

    private void panel_fifthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fifthMouseEntered

    private void panel_fifthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fifthMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fifthMouseExited

    private void panel_fourthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fourthMouseClicked

    private void panel_fourthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fourthMouseEntered

    private void panel_fourthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fourthMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_fourthMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_dept_fifth;
    private javax.swing.JLabel label_dept_first;
    private javax.swing.JLabel label_dept_fourth;
    private javax.swing.JLabel label_dept_second;
    private javax.swing.JLabel label_dept_sixth;
    private javax.swing.JLabel label_dept_third;
    private javax.swing.JLabel label_hallName;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_name_fifth;
    private javax.swing.JLabel label_name_first;
    private javax.swing.JLabel label_name_fourth;
    private javax.swing.JLabel label_name_second;
    private javax.swing.JLabel label_name_sixth;
    private javax.swing.JLabel label_name_third;
    private javax.swing.JPanel panel_fifth;
    private javax.swing.JPanel panel_first;
    private javax.swing.JPanel panel_fourth;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_second;
    private javax.swing.JPanel panel_sixth;
    private javax.swing.JPanel panel_third;
    // End of variables declaration//GEN-END:variables
}
