/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.room;

import hallconnect.database.CentralController;
import hallconnect.provost.provostDashboard;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ThirdFloor extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    private String hall;

    /**
     * Creates new form loginPage
     */
    public ThirdFloor(CentralController controller, String hall) {
        this.hall=hall;
        this.controller = controller;
        initComponents();
    }

    public ThirdFloor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        label_login = new javax.swing.JLabel();
        panel_309 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        label_total_309 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        label_vacant_309 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        panel_304 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_vacant_304 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_total_304 = new javax.swing.JLabel();
        panel_308 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        label_total_308 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        label_vacant_308 = new javax.swing.JLabel();
        panel_303 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        label_total_303 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        label_vacant_303 = new javax.swing.JLabel();
        panel_302 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        label_total_302 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        label_vacant_302 = new javax.swing.JLabel();
        panel_301 = new javax.swing.JPanel();
        label_ = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        label_total_301 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        label_vacant_301 = new javax.swing.JLabel();
        panel_307 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_vacant_307 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_total_307 = new javax.swing.JLabel();
        panel_306 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        label_vacant_306 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_total_306 = new javax.swing.JLabel();
        panel_305 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        label_vacant_305 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_total_305 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 140, 60));

        label_login.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setText("THIRD FLOOR");
        panel_parent.add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 400, 50));

        panel_309.setBackground(new java.awt.Color(0, 51, 51));
        panel_309.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_309.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_309MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_309MouseExited(evt);
            }
        });
        panel_309.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("309");
        panel_309.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("TOTAL:");
        panel_309.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        label_total_309.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_309.setForeground(new java.awt.Color(255, 255, 255));
        label_total_309.setText("TOTAL:");
        panel_309.add(label_total_309, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("VACANT:");
        panel_309.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_309.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_309.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_309.setText("TOTAL:");
        panel_309.add(label_vacant_309, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        panel_parent.add(panel_309, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 270, 170));

        btn_exit.setBackground(new java.awt.Color(102, 102, 102));
        btn_exit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/exit.png"))); // NOI18N
        btn_exit.setText(" EXIT");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 160, 60));

        panel_304.setBackground(new java.awt.Color(0, 51, 51));
        panel_304.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_304.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_304MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_304MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_304MouseExited(evt);
            }
        });
        panel_304.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VACANT:");
        panel_304.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_304.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_304.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_304.setText("TOTAL:");
        panel_304.add(label_vacant_304, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL:");
        panel_304.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("304");
        panel_304.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        label_total_304.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_304.setForeground(new java.awt.Color(255, 255, 255));
        label_total_304.setText("TOTAL:");
        panel_304.add(label_total_304, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        panel_parent.add(panel_304, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 270, 170));

        panel_308.setBackground(new java.awt.Color(0, 51, 51));
        panel_308.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_308.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_308MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_308MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_308MouseExited(evt);
            }
        });
        panel_308.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("308");
        panel_308.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("TOTAL:");
        panel_308.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        label_total_308.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_308.setForeground(new java.awt.Color(255, 255, 255));
        label_total_308.setText("TOTAL:");
        panel_308.add(label_total_308, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("VACANT:");
        panel_308.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_308.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_308.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_308.setText("TOTAL:");
        panel_308.add(label_vacant_308, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        panel_parent.add(panel_308, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 270, 170));

        panel_303.setBackground(new java.awt.Color(0, 51, 51));
        panel_303.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_303.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_303MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_303MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_303MouseExited(evt);
            }
        });
        panel_303.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("303");
        panel_303.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        jLabel47.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("TOTAL:");
        panel_303.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        label_total_303.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_303.setForeground(new java.awt.Color(255, 255, 255));
        label_total_303.setText("TOTAL:");
        panel_303.add(label_total_303, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jLabel49.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("VACANT:");
        panel_303.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_303.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_303.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_303.setText("TOTAL:");
        panel_303.add(label_vacant_303, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        panel_parent.add(panel_303, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 180, 280, 170));

        panel_302.setBackground(new java.awt.Color(0, 51, 51));
        panel_302.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_302.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_302MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_302MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_302MouseExited(evt);
            }
        });
        panel_302.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("302");
        panel_302.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        jLabel42.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("TOTAL:");
        panel_302.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        label_total_302.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_302.setForeground(new java.awt.Color(255, 255, 255));
        label_total_302.setText("TOTAL:");
        panel_302.add(label_total_302, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jLabel44.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("VACANT:");
        panel_302.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_302.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_302.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_302.setText("TOTAL:");
        panel_302.add(label_vacant_302, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        panel_parent.add(panel_302, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 370, 280, 170));

        panel_301.setBackground(new java.awt.Color(0, 51, 51));
        panel_301.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_301.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_301MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_301MouseExited(evt);
            }
        });
        panel_301.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        label_.setForeground(new java.awt.Color(255, 255, 255));
        label_.setText("301");
        panel_301.add(label_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("TOTAL:");
        panel_301.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        label_total_301.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_301.setForeground(new java.awt.Color(255, 255, 255));
        label_total_301.setText("TOTAL:");
        panel_301.add(label_total_301, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("VACANT:");
        panel_301.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_301.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_301.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_301.setText("TOTAL:");
        panel_301.add(label_vacant_301, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        panel_parent.add(panel_301, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 280, 170));

        panel_307.setBackground(new java.awt.Color(0, 51, 51));
        panel_307.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_307.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_307MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_307MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_307MouseExited(evt);
            }
        });
        panel_307.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VACANT:");
        panel_307.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_307.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_307.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_307.setText("TOTAL:");
        panel_307.add(label_vacant_307, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL:");
        panel_307.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("307");
        panel_307.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        label_total_307.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_307.setForeground(new java.awt.Color(255, 255, 255));
        label_total_307.setText("TOTAL:");
        panel_307.add(label_total_307, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        panel_parent.add(panel_307, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 170));

        panel_306.setBackground(new java.awt.Color(0, 51, 51));
        panel_306.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_306.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_306MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_306MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_306MouseExited(evt);
            }
        });
        panel_306.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VACANT:");
        panel_306.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_306.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_306.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_306.setText("TOTAL:");
        panel_306.add(label_vacant_306, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL:");
        panel_306.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("306");
        panel_306.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        label_total_306.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_306.setForeground(new java.awt.Color(255, 255, 255));
        label_total_306.setText("TOTAL:");
        panel_306.add(label_total_306, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        panel_parent.add(panel_306, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 270, 170));

        panel_305.setBackground(new java.awt.Color(0, 51, 51));
        panel_305.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_305.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_305MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_305MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_305MouseExited(evt);
            }
        });
        panel_305.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("VACANT:");
        panel_305.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        label_vacant_305.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_vacant_305.setForeground(new java.awt.Color(255, 255, 255));
        label_vacant_305.setText("TOTAL:");
        panel_305.add(label_vacant_305, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL:");
        panel_305.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("305");
        panel_305.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 30));

        label_total_305.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        label_total_305.setForeground(new java.awt.Color(255, 255, 255));
        label_total_305.setText("TOTAL:");
        panel_305.add(label_total_305, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        panel_parent.add(panel_305, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 270, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void panel_309MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_309MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_309.setBackground(clr);
    }//GEN-LAST:event_panel_309MouseEntered

    private void panel_309MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_309MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_309.setBackground(clr);
    }//GEN-LAST:event_panel_309MouseExited

    private void panel_304MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_304MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_304.setBackground(clr);
    }//GEN-LAST:event_panel_304MouseEntered

    private void panel_304MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_304MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_304.setBackground(clr);
    }//GEN-LAST:event_panel_304MouseExited

    private void panel_304MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_304MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_panel_304MouseClicked

    private void panel_308MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_308MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_308MouseClicked

    private void panel_308MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_308MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_308.setBackground(clr);
    }//GEN-LAST:event_panel_308MouseEntered

    private void panel_308MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_308MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_308.setBackground(clr);
    }//GEN-LAST:event_panel_308MouseExited

    private void panel_303MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_303MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_303MouseClicked

    private void panel_303MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_303MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_303.setBackground(clr);
    }//GEN-LAST:event_panel_303MouseEntered

    private void panel_303MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_303MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_303.setBackground(clr);
    }//GEN-LAST:event_panel_303MouseExited

    private void panel_302MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_302MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_302MouseClicked

    private void panel_302MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_302MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_302.setBackground(clr);
    }//GEN-LAST:event_panel_302MouseEntered

    private void panel_302MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_302MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_302.setBackground(clr);
    }//GEN-LAST:event_panel_302MouseExited

    private void panel_301MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_301MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_301.setBackground(clr);
    }//GEN-LAST:event_panel_301MouseEntered

    private void panel_301MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_301MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_301.setBackground(clr);
    }//GEN-LAST:event_panel_301MouseExited

    private void panel_307MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_307MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_307MouseClicked

    private void panel_307MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_307MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_307.setBackground(clr);
    }//GEN-LAST:event_panel_307MouseEntered

    private void panel_307MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_307MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_307.setBackground(clr);
    }//GEN-LAST:event_panel_307MouseExited

    private void panel_306MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_306MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_306MouseClicked

    private void panel_306MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_306MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_306.setBackground(clr);
    }//GEN-LAST:event_panel_306MouseEntered

    private void panel_306MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_306MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_306.setBackground(clr);
    }//GEN-LAST:event_panel_306MouseExited

    private void panel_305MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_305MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_305MouseClicked

    private void panel_305MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_305MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panel_305.setBackground(clr);
    }//GEN-LAST:event_panel_305MouseEntered

    private void panel_305MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_305MouseExited
        // TODO add your handling code here:
        Color clr  = new Color(0,51,51);
        panel_305.setBackground(clr);
    }//GEN-LAST:event_panel_305MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdFloor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_total_301;
    private javax.swing.JLabel label_total_302;
    private javax.swing.JLabel label_total_303;
    private javax.swing.JLabel label_total_304;
    private javax.swing.JLabel label_total_305;
    private javax.swing.JLabel label_total_306;
    private javax.swing.JLabel label_total_307;
    private javax.swing.JLabel label_total_308;
    private javax.swing.JLabel label_total_309;
    private javax.swing.JLabel label_vacant_301;
    private javax.swing.JLabel label_vacant_302;
    private javax.swing.JLabel label_vacant_303;
    private javax.swing.JLabel label_vacant_304;
    private javax.swing.JLabel label_vacant_305;
    private javax.swing.JLabel label_vacant_306;
    private javax.swing.JLabel label_vacant_307;
    private javax.swing.JLabel label_vacant_308;
    private javax.swing.JLabel label_vacant_309;
    private javax.swing.JPanel panel_301;
    private javax.swing.JPanel panel_302;
    private javax.swing.JPanel panel_303;
    private javax.swing.JPanel panel_304;
    private javax.swing.JPanel panel_305;
    private javax.swing.JPanel panel_306;
    private javax.swing.JPanel panel_307;
    private javax.swing.JPanel panel_308;
    private javax.swing.JPanel panel_309;
    private javax.swing.JPanel panel_parent;
    // End of variables declaration//GEN-END:variables
}
