/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.student;

import hallconnect.BH_Associates;
import hallconnect.MH_Associates;
import hallconnect.MMH_Associates;
import hallconnect.database.CentralController;
import hallconnect.database.DbConnection;
import hallconnect.signup.loginPage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class StudentDashboard extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    private String student_username;

    /**
     * Creates new form loginPage
     */
    public StudentDashboard(CentralController controller, String student_username) {
        this.controller = controller;
        this.student_username = student_username;
        initComponents();
        showData();
    }

    public StudentDashboard() {
        initComponents();
    }

    void showData() {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT name,reg,session,contact,email,blood FROM student where username=?");
            pst.setString(1, student_username);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                label_blood.setText(rs.getString("blood"));
                lable_reg.setText(rs.getString("reg"));
                label_contact.setText(rs.getString("contact"));
                label_name.setText(rs.getString("name"));
                label_email.setText(rs.getString("email"));
                label_session.setText(rs.getString("session"));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_welcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lable_reg = new javax.swing.JLabel();
        label_home19 = new javax.swing.JLabel();
        label_home20 = new javax.swing.JLabel();
        label_home21 = new javax.swing.JLabel();
        label_home22 = new javax.swing.JLabel();
        label_home23 = new javax.swing.JLabel();
        label_home24 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_session = new javax.swing.JLabel();
        label_contact = new javax.swing.JLabel();
        label_blood = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        panel_clearence = new javax.swing.JPanel();
        label_home2 = new javax.swing.JLabel();
        label_home3 = new javax.swing.JLabel();
        panel_fee = new javax.swing.JPanel();
        label_home4 = new javax.swing.JLabel();
        label_home5 = new javax.swing.JLabel();
        panel_notice = new javax.swing.JPanel();
        label_home8 = new javax.swing.JLabel();
        label_home9 = new javax.swing.JLabel();
        panel_complain = new javax.swing.JPanel();
        label_home10 = new javax.swing.JLabel();
        panel_associates = new javax.swing.JPanel();
        label_home12 = new javax.swing.JLabel();
        label_home13 = new javax.swing.JLabel();
        panel_room = new javax.swing.JPanel();
        label_home7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 193, 260, 10));

        label_welcome.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_welcome.setForeground(new java.awt.Color(255, 255, 255));
        label_welcome.setText("Welcome");
        panel_parent.add(label_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 190, 50));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lable_reg.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lable_reg.setForeground(new java.awt.Color(255, 255, 255));
        lable_reg.setText("Name           :");
        jPanel2.add(lable_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 360, 30));

        label_home19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home19.setForeground(new java.awt.Color(255, 255, 255));
        label_home19.setText("Reg no.        :");
        jPanel2.add(label_home19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        label_home20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home20.setForeground(new java.awt.Color(255, 255, 255));
        label_home20.setText("Session        :");
        jPanel2.add(label_home20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        label_home21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home21.setForeground(new java.awt.Color(255, 255, 255));
        label_home21.setText("Contact no.  :");
        jPanel2.add(label_home21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        label_home22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home22.setForeground(new java.awt.Color(255, 255, 255));
        label_home22.setText("E-mail           :");
        jPanel2.add(label_home22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        label_home23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home23.setForeground(new java.awt.Color(255, 255, 255));
        label_home23.setText("Blood            :");
        jPanel2.add(label_home23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        label_home24.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_home24.setForeground(new java.awt.Color(255, 255, 255));
        label_home24.setText("Name           :");
        jPanel2.add(label_home24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        label_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("Name           :");
        jPanel2.add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 360, 30));

        label_session.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_session.setForeground(new java.awt.Color(255, 255, 255));
        label_session.setText("Name           :");
        jPanel2.add(label_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 360, 30));

        label_contact.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_contact.setForeground(new java.awt.Color(255, 255, 255));
        label_contact.setText("Name           :");
        jPanel2.add(label_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 360, 30));

        label_blood.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_blood.setForeground(new java.awt.Color(255, 255, 255));
        label_blood.setText("Name           :");
        jPanel2.add(label_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 360, 30));

        label_email.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("Name           :");
        jPanel2.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 360, 30));

        panel_parent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 670, 320));

        panel_clearence.setBackground(new java.awt.Color(153, 0, 51));
        panel_clearence.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_clearence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_clearenceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_clearenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_clearenceMouseExited(evt);
            }
        });

        label_home2.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home2.setForeground(new java.awt.Color(255, 255, 255));
        label_home2.setText("Clearnece");

        label_home3.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home3.setForeground(new java.awt.Color(255, 255, 255));
        label_home3.setText("Application");

        javax.swing.GroupLayout panel_clearenceLayout = new javax.swing.GroupLayout(panel_clearence);
        panel_clearence.setLayout(panel_clearenceLayout);
        panel_clearenceLayout.setHorizontalGroup(
            panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clearenceLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clearenceLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(label_home2))
                    .addComponent(label_home3))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panel_clearenceLayout.setVerticalGroup(
            panel_clearenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_clearenceLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(label_home2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_home3)
                .addGap(21, 21, 21))
        );

        panel_parent.add(panel_clearence, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 260, 140));

        panel_fee.setBackground(new java.awt.Color(153, 0, 51));
        panel_fee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_feeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_feeMouseExited(evt);
            }
        });

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("Hall Fee");

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("Payment");

        javax.swing.GroupLayout panel_feeLayout = new javax.swing.GroupLayout(panel_fee);
        panel_fee.setLayout(panel_feeLayout);
        panel_feeLayout.setHorizontalGroup(
            panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_feeLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_home4)
                    .addComponent(label_home5))
                .addGap(62, 62, 62))
        );
        panel_feeLayout.setVerticalGroup(
            panel_feeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_home4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home5)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_parent.add(panel_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 260, 140));

        panel_notice.setBackground(new java.awt.Color(153, 0, 51));
        panel_notice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_notice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_noticeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_noticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_noticeMouseExited(evt);
            }
        });

        label_home8.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home8.setForeground(new java.awt.Color(255, 255, 255));
        label_home8.setText("Notice");

        label_home9.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home9.setForeground(new java.awt.Color(255, 255, 255));
        label_home9.setText("Board");

        javax.swing.GroupLayout panel_noticeLayout = new javax.swing.GroupLayout(panel_notice);
        panel_notice.setLayout(panel_noticeLayout);
        panel_noticeLayout.setHorizontalGroup(
            panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_noticeLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_home8)
                    .addComponent(label_home9))
                .addGap(76, 76, 76))
        );
        panel_noticeLayout.setVerticalGroup(
            panel_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_noticeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label_home8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home9)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel_parent.add(panel_notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 260, 140));

        panel_complain.setBackground(new java.awt.Color(153, 0, 51));
        panel_complain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_complain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_complainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_complainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_complainMouseExited(evt);
            }
        });

        label_home10.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home10.setForeground(new java.awt.Color(255, 255, 255));
        label_home10.setText("Complain");

        javax.swing.GroupLayout panel_complainLayout = new javax.swing.GroupLayout(panel_complain);
        panel_complain.setLayout(panel_complainLayout);
        panel_complainLayout.setHorizontalGroup(
            panel_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_complainLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label_home10)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panel_complainLayout.setVerticalGroup(
            panel_complainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_complainLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(label_home10)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panel_parent.add(panel_complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 260, 140));

        panel_associates.setBackground(new java.awt.Color(153, 0, 51));
        panel_associates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_associates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_associatesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_associatesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_associatesMouseExited(evt);
            }
        });

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("Hall");

        label_home13.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home13.setForeground(new java.awt.Color(255, 255, 255));
        label_home13.setText("Associates");

        javax.swing.GroupLayout panel_associatesLayout = new javax.swing.GroupLayout(panel_associates);
        panel_associates.setLayout(panel_associatesLayout);
        panel_associatesLayout.setHorizontalGroup(
            panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_associatesLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_associatesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(label_home12))
                    .addComponent(label_home13))
                .addGap(37, 37, 37))
        );
        panel_associatesLayout.setVerticalGroup(
            panel_associatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_associatesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_home12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_home13)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panel_parent.add(panel_associates, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 260, 140));

        panel_room.setBackground(new java.awt.Color(153, 0, 51));
        panel_room.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_roomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_roomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_roomMouseExited(evt);
            }
        });

        label_home7.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        label_home7.setForeground(new java.awt.Color(255, 255, 255));
        label_home7.setText("Room");

        javax.swing.GroupLayout panel_roomLayout = new javax.swing.GroupLayout(panel_room);
        panel_room.setLayout(panel_roomLayout);
        panel_roomLayout.setHorizontalGroup(
            panel_roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_roomLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(label_home7)
                .addGap(85, 85, 85))
        );
        panel_roomLayout.setVerticalGroup(
            panel_roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_roomLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(label_home7)
                .addGap(47, 47, 47))
        );

        panel_parent.add(panel_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 260, 140));

        btn_exit.setBackground(new java.awt.Color(102, 102, 102));
        btn_exit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/exit.png"))); // NOI18N
        btn_exit.setText(" EXIT");
        btn_exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        panel_parent.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 600, 200, 70));

        btn_logout.setBackground(new java.awt.Color(102, 102, 102));
        btn_logout.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/logout.png"))); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panel_parent.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 200, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_feeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_fee.setBackground(clr);
    }//GEN-LAST:event_panel_feeMouseEntered

    private void panel_noticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_noticeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_notice.setBackground(clr);
    }//GEN-LAST:event_panel_noticeMouseEntered

    private void panel_complainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_complain.setBackground(clr);
    }//GEN-LAST:event_panel_complainMouseEntered

    private void panel_associatesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_associatesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_associates.setBackground(clr);
    }//GEN-LAST:event_panel_associatesMouseEntered

    private void panel_clearenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearenceMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_clearence.setBackground(clr);
    }//GEN-LAST:event_panel_clearenceMouseEntered

    private void panel_feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_feeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_fee.setBackground(clr);
    }//GEN-LAST:event_panel_feeMouseExited

    private void panel_noticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_noticeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_notice.setBackground(clr);
    }//GEN-LAST:event_panel_noticeMouseExited

    private void panel_complainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_complain.setBackground(clr);
    }//GEN-LAST:event_panel_complainMouseExited

    private void panel_associatesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_associatesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_associates.setBackground(clr);
    }//GEN-LAST:event_panel_associatesMouseExited

    private void panel_clearenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearenceMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_clearence.setBackground(clr);
    }//GEN-LAST:event_panel_clearenceMouseExited

    private void panel_roomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_roomMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_room.setBackground(clr);

    }//GEN-LAST:event_panel_roomMouseEntered

    private void panel_roomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_roomMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_room.setBackground(clr);
    }//GEN-LAST:event_panel_roomMouseExited

    private void panel_feeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_feeMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        StudentFeeConfirmation StudentFeeConfirmation = new StudentFeeConfirmation(controller, student_username, label_session.getText());
        StudentFeeConfirmation.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_feeMouseClicked

    private void panel_roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_roomMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        StudentRoomDetails StudentRoomDetails = new StudentRoomDetails(controller);
        StudentRoomDetails.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_panel_roomMouseClicked

    private void panel_complainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainMouseClicked
        // TODO add your handling code here:

        controller.addFrame(this);
        StudentComplain stdcmp = new StudentComplain(controller, student_username);
        stdcmp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_complainMouseClicked

    private void panel_associatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_associatesMouseClicked
        // TODO add your handling code here:
        String hall_name = null;
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT hall_name FROM room_details where username=?");
            pst.setString(1, student_username);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                hall_name = rs.getString("hall_name");
                if (hall_name.equals("BANGABONDHU HALL")) {
                    controller.addFrame(this);
                    BH_Associates bh = new BH_Associates(controller);
                    bh.setVisible(true);
                    this.setVisible(false);
                } else if (hall_name.equals("MUKTIJODDHA HALL")) {
                    controller.addFrame(this);
                    MH_Associates bh = new MH_Associates(controller);
                    bh.setVisible(true);
                    this.setVisible(false);
                } else {
                    controller.addFrame(this);
                    MMH_Associates bh = new MMH_Associates(controller);
                    bh.setVisible(true);
                    this.setVisible(false);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_panel_associatesMouseClicked

    private void panel_clearenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearenceMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        StudentClearence StudentClearence = new StudentClearence(controller,student_username,lable_reg.getText(),label_session.getText(),label_contact.getText(),label_email.getText(),label_blood.getText());
        StudentClearence.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_panel_clearenceMouseClicked

    private void panel_noticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_noticeMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        new StudentNoticeBoard(controller).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_noticeMouseClicked

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:

        loginPage lg = new loginPage();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_blood;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_home10;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home19;
    private javax.swing.JLabel label_home2;
    private javax.swing.JLabel label_home20;
    private javax.swing.JLabel label_home21;
    private javax.swing.JLabel label_home22;
    private javax.swing.JLabel label_home23;
    private javax.swing.JLabel label_home24;
    private javax.swing.JLabel label_home3;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JLabel label_home7;
    private javax.swing.JLabel label_home8;
    private javax.swing.JLabel label_home9;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_session;
    private javax.swing.JLabel label_welcome;
    private javax.swing.JLabel lable_reg;
    private javax.swing.JPanel panel_associates;
    private javax.swing.JPanel panel_clearence;
    private javax.swing.JPanel panel_complain;
    private javax.swing.JPanel panel_fee;
    private javax.swing.JPanel panel_notice;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_room;
    // End of variables declaration//GEN-END:variables
}
