/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.student;

import hallconnect.database.CentralController;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class StudentNoticeBoard extends javax.swing.JFrame {
  private CentralController controller = new CentralController();
    /**
     * Creates new form loginPage
     */
    public StudentNoticeBoard(CentralController controller) {
        this.controller=controller;
        initComponents();
    }
    public StudentNoticeBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_login = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel_notice_1 = new javax.swing.JPanel();
        label_home12 = new javax.swing.JLabel();
        panel_notice_2 = new javax.swing.JPanel();
        label_home13 = new javax.swing.JLabel();
        panel_notice_3 = new javax.swing.JPanel();
        label_home14 = new javax.swing.JLabel();
        panel_notice_name_1 = new javax.swing.JPanel();
        panel_notice_name_2 = new javax.swing.JPanel();
        panel_notice_name_3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText("HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(label_hallconnect)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 130));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, 140, 54));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 270, 10));

        label_login.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setText("Notice Board");
        panel_parent.add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 50));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_notice_1.setBackground(new java.awt.Color(153, 0, 51));
        panel_notice_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_notice_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_notice_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_notice_1MouseExited(evt);
            }
        });
        panel_notice_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("Notice - 01");
        panel_notice_1.add(label_home12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jPanel3.add(panel_notice_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 70));

        panel_notice_2.setBackground(new java.awt.Color(153, 0, 51));
        panel_notice_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_notice_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_notice_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_notice_2MouseExited(evt);
            }
        });
        panel_notice_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home13.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        label_home13.setForeground(new java.awt.Color(255, 255, 255));
        label_home13.setText("Notice - 02");
        panel_notice_2.add(label_home13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jPanel3.add(panel_notice_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 70));

        panel_notice_3.setBackground(new java.awt.Color(153, 0, 51));
        panel_notice_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_notice_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_notice_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_notice_3MouseExited(evt);
            }
        });
        panel_notice_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home14.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        label_home14.setForeground(new java.awt.Color(255, 255, 255));
        label_home14.setText("Notice - 03");
        panel_notice_3.add(label_home14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jPanel3.add(panel_notice_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 290, 70));

        javax.swing.GroupLayout panel_notice_name_1Layout = new javax.swing.GroupLayout(panel_notice_name_1);
        panel_notice_name_1.setLayout(panel_notice_name_1Layout);
        panel_notice_name_1Layout.setHorizontalGroup(
            panel_notice_name_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panel_notice_name_1Layout.setVerticalGroup(
            panel_notice_name_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel3.add(panel_notice_name_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 1020, 70));

        javax.swing.GroupLayout panel_notice_name_2Layout = new javax.swing.GroupLayout(panel_notice_name_2);
        panel_notice_name_2.setLayout(panel_notice_name_2Layout);
        panel_notice_name_2Layout.setHorizontalGroup(
            panel_notice_name_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panel_notice_name_2Layout.setVerticalGroup(
            panel_notice_name_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel3.add(panel_notice_name_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 1020, 70));

        javax.swing.GroupLayout panel_notice_name_3Layout = new javax.swing.GroupLayout(panel_notice_name_3);
        panel_notice_name_3.setLayout(panel_notice_name_3Layout);
        panel_notice_name_3Layout.setHorizontalGroup(
            panel_notice_name_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panel_notice_name_3Layout.setVerticalGroup(
            panel_notice_name_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel3.add(panel_notice_name_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 1020, 70));

        panel_parent.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1440, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void panel_notice_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_1MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_notice_1.setBackground(clr);
    }//GEN-LAST:event_panel_notice_1MouseEntered

    private void panel_notice_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_1MouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_notice_1.setBackground(clr);
    }//GEN-LAST:event_panel_notice_1MouseExited

    private void panel_notice_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_notice_2MouseEntered

    private void panel_notice_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_notice_2MouseExited

    private void panel_notice_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_notice_3MouseEntered

    private void panel_notice_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_notice_3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_notice_3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentNoticeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentNoticeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentNoticeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentNoticeBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentNoticeBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home14;
    private javax.swing.JLabel label_login;
    private javax.swing.JPanel panel_notice_1;
    private javax.swing.JPanel panel_notice_2;
    private javax.swing.JPanel panel_notice_3;
    private javax.swing.JPanel panel_notice_name_1;
    private javax.swing.JPanel panel_notice_name_2;
    private javax.swing.JPanel panel_notice_name_3;
    private javax.swing.JPanel panel_parent;
    // End of variables declaration//GEN-END:variables
}
