/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.provost;

import hallconnect.room.RoomSelection;
import hallconnect.database.CentralController;
import hallconnect.database.DbConnection;
import hallconnect.signup.loginPage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ProvostHallFee extends javax.swing.JFrame {

    private CentralController controller = new CentralController();

    String provost_username; // provost username
    String hall_name;
    String student_name = null;
    String session = null;
    String semestr = null;

    /**
     * Creates new form loginPage
     */
    public ProvostHallFee(CentralController controller, String provost_username) {
        this.controller = controller;
        this.provost_username = provost_username;

        initComponents();
        showRechord(provost_username);
    }

    public ProvostHallFee(String username) {
        this.provost_username = provost_username;
        initComponents();
        showRechord(provost_username);

    }

    public ProvostHallFee() {
        initComponents();
    }

//    BANGABONDHU HALL
//MUKTIJODDHA HALL
//BANGAMATA HALL
    void showRechord(String provost_username) {
        DefaultTableModel model = (DefaultTableModel) table_feeRequest.getModel();

        hall_name = switch (provost_username) {
            case "abu_naser" ->
                "BANGABONDHU HALL";
            case "naznin_ara" ->
                "BANGAMATA HALL";
            default ->
                "MUKTIJODDHA HALL";
        };
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM pending_payment WHERE hallName=?");
            pst.setString(1, hall_name);
            ResultSet rs = pst.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                String username = rs.getString("username");
                String session = rs.getString("session");
                String semester = rs.getString("semester");
                String method = rs.getString("method");
                String transaction_id = rs.getString("transaction_id");
                Object obj[] = {username, session, semester, method, transaction_id};
                model.addRow(obj);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    boolean delete() {
        try {
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("DELETE from pending_payment where username = ? AND semester=?");
            pst.setString(1, student_name);
            pst.setString(2, semestr);
            int row = pst.executeUpdate();
            return row > 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_feeRequest = new javax.swing.JTable();
        btn_accept = new javax.swing.JButton();
        btn_reject1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        date_year = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_semester = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        btn_accept1 = new javax.swing.JButton();
        btn_reject2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText(" HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(587, 587, 587)
                .addComponent(label_hallconnect)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        table_feeRequest.setBackground(new java.awt.Color(0, 51, 51));
        table_feeRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        table_feeRequest.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        table_feeRequest.setForeground(new java.awt.Color(255, 255, 255));
        table_feeRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "session", "semester", "method", "transaction id"
            }
        ));
        table_feeRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_feeRequestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_feeRequest);

        panel_parent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 670, 450));

        btn_accept.setBackground(new java.awt.Color(102, 102, 102));
        btn_accept.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/add2.png"))); // NOI18N
        btn_accept.setText("ADD");
        btn_accept.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });
        panel_parent.add(btn_accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, 180, 60));

        btn_reject1.setBackground(new java.awt.Color(102, 102, 102));
        btn_reject1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_reject1.setForeground(new java.awt.Color(255, 255, 255));
        btn_reject1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/delete.png"))); // NOI18N
        btn_reject1.setText("DELETE");
        btn_reject1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_reject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reject1ActionPerformed(evt);
            }
        });
        panel_parent.add(btn_reject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 660, 180, 60));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLICK ANY ROW TO SELECT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panel_parent.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 500, 50));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 140, 60));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(date_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, 40));

        jLabel2.setBackground(new java.awt.Color(153, 102, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HALL FEE :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel3.setBackground(new java.awt.Color(153, 102, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SESSION :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        combo_semester.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        combo_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        combo_semester.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(combo_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 150, 40));

        jLabel4.setBackground(new java.awt.Color(153, 102, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEMESTER :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txt_amount.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jPanel4.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 222, 150, 40));

        panel_parent.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 560, 450));

        btn_accept1.setBackground(new java.awt.Color(102, 102, 102));
        btn_accept1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_accept1.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/add2.png"))); // NOI18N
        btn_accept1.setText("ACCEPT");
        btn_accept1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accept1ActionPerformed(evt);
            }
        });
        panel_parent.add(btn_accept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 180, 60));

        btn_reject2.setBackground(new java.awt.Color(102, 102, 102));
        btn_reject2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_reject2.setForeground(new java.awt.Color(255, 255, 255));
        btn_reject2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/delete.png"))); // NOI18N
        btn_reject2.setText("REJECT");
        btn_reject2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_reject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reject2ActionPerformed(evt);
            }
        });
        panel_parent.add(btn_reject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_reject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reject1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_reject1ActionPerformed

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
        try {
            // Get selected year as an integer
            int selectedYear = date_year.getYear();
            // Convert to string
            String session = String.valueOf(selectedYear);
            String semester = combo_semester.getSelectedItem().toString();
            String amount = txt_amount.getText();
            Connection con = DbConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("INSERT INTO semester (session,semester,fee) values (?,?,?)");
            pst.setString(1, session);
            pst.setString(2, semester);
            pst.setString(3, amount);
            int rowCount = pst.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Semester Fee Added Successfully");
                txt_amount.setText("");
                combo_semester.setSelectedItem("0");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_acceptActionPerformed

    private void table_feeRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_feeRequestMouseClicked
        // TODO add your handling code here:
        int row = table_feeRequest.getSelectedRow();
        student_name = table_feeRequest.getValueAt(row, 0).toString();
        session = table_feeRequest.getValueAt(row, 1).toString();
        semestr = table_feeRequest.getValueAt(row, 2).toString();


    }//GEN-LAST:event_table_feeRequestMouseClicked

    private void btn_accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accept1ActionPerformed
        // TODO add your handling code here:
        if (student_name == null || session == null || semestr == null) {
            JOptionPane.showMessageDialog(this, "Please Select any row to accept");
        } else {

            try {
                Connection con = DbConnection.getConnection();
                PreparedStatement pst = con.prepareStatement("INSERT INTO payment (username,session,semester,payment_status) values(?,?,?,?)");
                pst.setString(1, student_name);
                pst.setString(2, session);
                pst.setString(3, semestr);
                pst.setString(4, "Paid");
                int row = pst.executeUpdate();
                if (row > 0) {
                    delete();
                    JOptionPane.showMessageDialog(this, "Accepted Successfully");
                    showRechord(provost_username);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_btn_accept1ActionPerformed

    private void btn_reject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reject2ActionPerformed
        // TODO add your handling code here:
        if (student_name == null || session == null || semestr == null) {
            JOptionPane.showMessageDialog(this, "Please Select any row to accept");
        } else {
            if (delete()) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
                showRechord(provost_username);
            }
        }
    }//GEN-LAST:event_btn_reject2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvostHallFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvostHallFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvostHallFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvostHallFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvostHallFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_accept1;
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_reject1;
    private javax.swing.JButton btn_reject2;
    private javax.swing.JComboBox<String> combo_semester;
    private com.toedter.calendar.JYearChooser date_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JTable table_feeRequest;
    private javax.swing.JTextField txt_amount;
    // End of variables declaration//GEN-END:variables
}
