/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallconnect.provost;

import hallconnect.BH_Associates;
import hallconnect.MH_Associates;
import hallconnect.MMH_Associates;
import hallconnect.room.RoomSelection;
import hallconnect.database.CentralController;
import hallconnect.database.DbConnection;
import hallconnect.signup.loginPage;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class provostClearance extends javax.swing.JFrame {

    private CentralController controller = new CentralController();
    String provost_username; // provost username
    String hall_name;
    String contact = "";
    String student_username = ""; // student name
    String session = "";

    /**
     * Creates new form loginPage
     */
    public provostClearance(CentralController controller, String provost_username) {
        this.controller = controller;
        this.provost_username = provost_username;

        initComponents();
        showRechord(provost_username);
    }

    public provostClearance(String provost_username) {
        this.provost_username = provost_username;
        initComponents();
        showRechord(provost_username);

    }

    public provostClearance() {
        initComponents();
    }

//    BANGABONDHU HALL
//MUKTIJODDHA HALL
//BANGAMATA HALL
    void showRechord(String provost_username) {

        hall_name = switch (provost_username) {
            case "abu_naser" ->
                "BANGABONDHU HALL";
            case "naznin_ara" ->
                "BANGAMATA HALL";
            default ->
                "MUKTIJODDHA HALL";
        };
        try {
            Connection con = DbConnection.getConnection();
            String query = "select username,session,contact from clearance where hallname=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, this.hall_name);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel table_model = (DefaultTableModel) table_info.getModel();
            // clear previous data
            table_model.setRowCount(0);
            // add new data
            while (rs.next()) {

                String username = rs.getString("username");
                String session = rs.getString("session");
                String contact = rs.getString("contact");

                Object obj[] = {username, session, contact};
                table_model.addRow(obj);

            }
            rs.close();
            con.close();
            pst.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void accept() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        panel_parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_hallconnect = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_info = new javax.swing.JTable();
        btn_accept = new javax.swing.JButton();
        btn_reject1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_session = new javax.swing.JLabel();
        label_contact = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel_complainBox = new javax.swing.JPanel();
        label_home4 = new javax.swing.JLabel();
        label_home15 = new javax.swing.JLabel();
        panel_hallFee = new javax.swing.JPanel();
        label_home12 = new javax.swing.JLabel();
        label_home13 = new javax.swing.JLabel();
        panel_clearance = new javax.swing.JPanel();
        label_home7 = new javax.swing.JLabel();
        label_home11 = new javax.swing.JLabel();
        panel_hallAsso = new javax.swing.JPanel();
        label_home6 = new javax.swing.JLabel();
        label_home10 = new javax.swing.JLabel();
        panel_addNotice = new javax.swing.JPanel();
        label_home5 = new javax.swing.JLabel();
        label_home9 = new javax.swing.JLabel();
        panel_signupRequest = new javax.swing.JPanel();
        label_home2 = new javax.swing.JLabel();
        label_home8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_parent.setBackground(new java.awt.Color(0, 51, 51));
        panel_parent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_parent.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.setPreferredSize(new java.awt.Dimension(1536, 800));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_hallconnect.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        label_hallconnect.setForeground(new java.awt.Color(255, 255, 255));
        label_hallconnect.setText(" HallConnect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(587, 587, 587)
                .addComponent(label_hallconnect)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_hallconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        table_info.setBackground(new java.awt.Color(0, 51, 51));
        table_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        table_info.setFont(new java.awt.Font("Calisto MT", 0, 16)); // NOI18N
        table_info.setForeground(new java.awt.Color(255, 255, 255));
        table_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "session", "contact"
            }
        ));
        table_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_info);

        panel_parent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 990, 350));

        btn_accept.setBackground(new java.awt.Color(102, 102, 102));
        btn_accept.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/add2.png"))); // NOI18N
        btn_accept.setText("ACCEPT");
        btn_accept.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });
        panel_parent.add(btn_accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 180, 60));

        btn_reject1.setBackground(new java.awt.Color(102, 102, 102));
        btn_reject1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_reject1.setForeground(new java.awt.Color(255, 255, 255));
        btn_reject1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/delete.png"))); // NOI18N
        btn_reject1.setText("REJECT");
        btn_reject1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_reject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reject1ActionPerformed(evt);
            }
        });
        panel_parent.add(btn_reject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 180, 60));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLICK ANY ROW TO SELECT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panel_parent.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 500, 50));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("contact:");
        panel_parent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, -1, 20));

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallconnect/icons/back1.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_parent.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 700, 170, 60));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("username: ");
        panel_parent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("session: ");
        panel_parent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, 20));

        label_username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 200, 20));

        label_session.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_session.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.add(label_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 180, 20));

        label_contact.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label_contact.setForeground(new java.awt.Color(255, 255, 255));
        panel_parent.add(label_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 590, 180, 20));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_complainBox.setBackground(new java.awt.Color(153, 0, 51));
        panel_complainBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_complainBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_complainBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_complainBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_complainBoxMouseExited(evt);
            }
        });
        panel_complainBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home4.setForeground(new java.awt.Color(255, 255, 255));
        label_home4.setText("COMPLAIN");
        panel_complainBox.add(label_home4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, -1));

        label_home15.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home15.setForeground(new java.awt.Color(255, 255, 255));
        label_home15.setText("BOX");
        panel_complainBox.add(label_home15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel4.add(panel_complainBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 340, 80));

        panel_hallFee.setBackground(new java.awt.Color(153, 0, 51));
        panel_hallFee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_hallFee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_hallFeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_hallFeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_hallFeeMouseExited(evt);
            }
        });
        panel_hallFee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home12.setForeground(new java.awt.Color(255, 255, 255));
        label_home12.setText("HALL FEE ");
        panel_hallFee.add(label_home12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        label_home13.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home13.setForeground(new java.awt.Color(255, 255, 255));
        label_home13.setText("REQUEST");
        panel_hallFee.add(label_home13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel4.add(panel_hallFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 80));

        panel_clearance.setBackground(new java.awt.Color(0, 153, 153));
        panel_clearance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_clearance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_clearanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_clearanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_clearanceMouseExited(evt);
            }
        });
        panel_clearance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home7.setForeground(new java.awt.Color(255, 255, 255));
        label_home7.setText("CLEARANCE");
        panel_clearance.add(label_home7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        label_home11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home11.setForeground(new java.awt.Color(255, 255, 255));
        label_home11.setText("REQUEST");
        panel_clearance.add(label_home11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jPanel4.add(panel_clearance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 340, 80));

        panel_hallAsso.setBackground(new java.awt.Color(153, 0, 51));
        panel_hallAsso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_hallAsso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_hallAssoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_hallAssoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_hallAssoMouseExited(evt);
            }
        });
        panel_hallAsso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home6.setForeground(new java.awt.Color(255, 255, 255));
        label_home6.setText("ASSOCIATES");
        panel_hallAsso.add(label_home6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, -1));

        label_home10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home10.setForeground(new java.awt.Color(255, 255, 255));
        label_home10.setText("HALL");
        panel_hallAsso.add(label_home10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));

        jPanel4.add(panel_hallAsso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, 80));

        panel_addNotice.setBackground(new java.awt.Color(153, 0, 51));
        panel_addNotice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_addNotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_addNoticeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_addNoticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_addNoticeMouseExited(evt);
            }
        });
        panel_addNotice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home5.setForeground(new java.awt.Color(255, 255, 255));
        label_home5.setText("NOTICE");
        panel_addNotice.add(label_home5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        label_home9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home9.setForeground(new java.awt.Color(255, 255, 255));
        label_home9.setText("ADD");
        panel_addNotice.add(label_home9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel4.add(panel_addNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 340, 80));

        panel_signupRequest.setBackground(new java.awt.Color(153, 0, 51));
        panel_signupRequest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_signupRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_signupRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_signupRequestMouseExited(evt);
            }
        });
        panel_signupRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_home2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home2.setForeground(new java.awt.Color(255, 255, 255));
        label_home2.setText("SIGNUP");
        panel_signupRequest.add(label_home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        label_home8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_home8.setForeground(new java.awt.Color(255, 255, 255));
        label_home8.setText("REQUEST");
        panel_signupRequest.add(label_home8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jPanel4.add(panel_signupRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 80));

        panel_parent.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 380, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
        if (student_username.equals("") || contact.equals("") || session.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Select Desired Row to Delete");
        } else {
            try {
                Connection con = DbConnection.getConnection();
                PreparedStatement pst1 = con.prepareStatement("DELETE FROM complain where username=?");
                PreparedStatement pst2 = con.prepareStatement("DELETE FROM payment where username=?");
                PreparedStatement pst3 = con.prepareStatement("DELETE FROM room_details where username=?");
                PreparedStatement pst4 = con.prepareStatement("DELETE FROM student where username=?");
                PreparedStatement pst5 = con.prepareStatement("DELETE FROM clearance where username=?");
                pst1.setString(1, student_username);
                pst2.setString(1, student_username);
                pst3.setString(1, student_username);
                pst4.setString(1, student_username);
                pst5.setString(1, student_username);
                int row = pst1.executeUpdate();
                row += pst2.executeUpdate();
                row += pst3.executeUpdate();
                row += pst4.executeUpdate();
                row += pst5.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Student Cleared");
                    showRechord(provost_username);
                    label_contact.setText("");
                    label_username.setText("");
                    label_session.setText("");

                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_reject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reject1ActionPerformed
        // TODO add your handling code here:
        if (student_username.equals("") || contact.equals("") || session.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Select Desired Row to Delete");
        } else {
            try {
                Connection con = DbConnection.getConnection();
               
                PreparedStatement pst5 = con.prepareStatement("DELETE FROM clearance where username=?");
                
                pst5.setString(1, student_username);
                int row =0;
                row += pst5.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Request Rejected");
                    showRechord(provost_username);
                    label_contact.setText("");
                    label_username.setText("");
                    label_session.setText("");
                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_btn_reject1ActionPerformed
    }
    private void table_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_infoMouseClicked
        // TODO add your handling code here:

        int rowNO = table_info.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) table_info.getModel();
        student_username = table.getValueAt(rowNO, 0).toString();
        session = table.getValueAt(rowNO, 1).toString();
        contact = table.getValueAt(rowNO, 2).toString();
        label_username.setText(student_username);
        label_contact.setText(contact);
        label_session.setText(session);
    }//GEN-LAST:event_table_infoMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        JFrame prev = controller.prevFrame();
        prev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void panel_complainBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainBoxMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        new ProvostComplainBox(controller, provost_username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_complainBoxMouseClicked

    private void panel_complainBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainBoxMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_complainBox.setBackground(clr);
    }//GEN-LAST:event_panel_complainBoxMouseEntered

    private void panel_complainBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_complainBoxMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_complainBox.setBackground(clr);
    }//GEN-LAST:event_panel_complainBoxMouseExited

    private void panel_hallFeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallFeeMouseClicked
        // TODO add your handling code here:
        ProvostHallFee hallfee = new ProvostHallFee(controller, provost_username);
        controller.addFrame(this);
        hallfee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_hallFeeMouseClicked

    private void panel_hallFeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallFeeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_hallFee.setBackground(clr);
    }//GEN-LAST:event_panel_hallFeeMouseEntered

    private void panel_hallFeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallFeeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_hallFee.setBackground(clr);
    }//GEN-LAST:event_panel_hallFeeMouseExited

    private void panel_clearanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearanceMouseClicked
        // TODO add your handling code here:
        controller.addFrame(this);
        provostClearance clr = new provostClearance(controller, provost_username);
        clr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_clearanceMouseClicked

    private void panel_clearanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearanceMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_clearance.setBackground(clr);
    }//GEN-LAST:event_panel_clearanceMouseEntered

    private void panel_clearanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_clearanceMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_clearanceMouseExited

    private void panel_hallAssoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallAssoMouseClicked
        // TODO add your handling code here:
        if ("abu_naser".equals(provost_username)) {
            controller.addFrame(this);
            BH_Associates bh = new BH_Associates(controller);
            bh.setVisible(true);
            this.setVisible(false);

        } else if ("naznin_ara".equals(provost_username)) {
            controller.addFrame(this);
            MMH_Associates bh = new MMH_Associates(controller);
            bh.setVisible(true);
            this.setVisible(false);
        } else {
            controller.addFrame(this);
            MH_Associates bh = new MH_Associates(controller);
            bh.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_panel_hallAssoMouseClicked

    private void panel_hallAssoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallAssoMouseEntered
        // TODO add your handling code here:

        Color clr = new Color(0, 153, 153);
        panel_hallAsso.setBackground(clr);
    }//GEN-LAST:event_panel_hallAssoMouseEntered

    private void panel_hallAssoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hallAssoMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_hallAsso.setBackground(clr);
    }//GEN-LAST:event_panel_hallAssoMouseExited

    private void panel_addNoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_addNoticeMouseClicked
        // TODO add your handling code here:controller.addFrame(this);
        new ProvostNotice(controller).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_addNoticeMouseClicked

    private void panel_addNoticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_addNoticeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_addNotice.setBackground(clr);
    }//GEN-LAST:event_panel_addNoticeMouseEntered

    private void panel_addNoticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_addNoticeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_addNotice.setBackground(clr);
    }//GEN-LAST:event_panel_addNoticeMouseExited

    private void panel_signupRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_signupRequestMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panel_signupRequest.setBackground(clr);
    }//GEN-LAST:event_panel_signupRequestMouseEntered

    private void panel_signupRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_signupRequestMouseExited
        // TODO add your handling code here:
        Color clr = new Color(153, 0, 51);
        panel_signupRequest.setBackground(clr);
    }//GEN-LAST:event_panel_signupRequestMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(provostClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(provostClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(provostClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(provostClearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new provostClearance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_reject1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_hallconnect;
    private javax.swing.JLabel label_home10;
    private javax.swing.JLabel label_home11;
    private javax.swing.JLabel label_home12;
    private javax.swing.JLabel label_home13;
    private javax.swing.JLabel label_home15;
    private javax.swing.JLabel label_home2;
    private javax.swing.JLabel label_home4;
    private javax.swing.JLabel label_home5;
    private javax.swing.JLabel label_home6;
    private javax.swing.JLabel label_home7;
    private javax.swing.JLabel label_home8;
    private javax.swing.JLabel label_home9;
    private javax.swing.JLabel label_session;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_addNotice;
    private javax.swing.JPanel panel_clearance;
    private javax.swing.JPanel panel_complainBox;
    private javax.swing.JPanel panel_hallAsso;
    private javax.swing.JPanel panel_hallFee;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_signupRequest;
    private javax.swing.JTable table_info;
    // End of variables declaration//GEN-END:variables
}
